### ISSUE TITLE
Torrents and a torrent RSS feed would be nice

### ISSUE THREAD

**Issue by crackwitz** [GyanD/codexffmpeg#100]
I just downloaded a package. The download crawled.

Torrents are an alternative that would offload this. BitTorrent's speed scales with the interest of the community.

For one file/release, you'd just need to call a command line utility to generate a `.torrent` file from the content. `.torrent` files are fairly small, just metadata. Anyone with the torrent file can then download the actual content from the swarm, but also from the original web server ("web seed").

For multiple files, but also releases over time, you can make a torrent RSS feed. People can subscribe to that feed in their torrent clients. Within minutes of a new release being announced, those torrent clients see it and start downloading. That'd initially be done from the web seed (web server) because nobody has the content yet. Torrent clients (should) prefer torrent seeds over web seeds, so as soon as the swarm has the file, there'd be very little web traffic from torrenting.

Unfortunately, I don't think there's a way to let normal web users enjoy the benefits of a seeded torrent. That'd require an user's browser to know how to download using the BitTorrent protocol.

**Comment by GyanD** [comment]
Do you mean the main site or the Github mirror?
