### ISSUE TITLE
"winget install ffmpeg-shared" gives "no package found..." error

### ISSUE THREAD

**Issue by emardee** [GyanD/codexffmpeg#101]
I am trying to use `winget install ffmpeg-shared` as a command on Win11 to installed the shared version. However running that give me "No package found matching input criteria." as an error message. 

If I try `winget install ffmpeg` I correctly get the non-shared version of package installed.

Is there an issue currently with the shared version?

**Comment by GyanD** [comment]
It should be `"FFmpeg (Shared)"`

**Comment by emardee** [comment]
Ah. Magic! Thanks. That was the syntax I needed.

For reference, I got it from this page: https://www.gyan.dev/ffmpeg/builds/ 
(...although it might be listed incorrectly on other pages too)
