### ISSUE TITLE
"winget install ffmpeg" gives "0x80070032 : The request is not supported." error

### ISSUE THREAD

**Issue by dream6502** [GyanD/codexffmpeg#103]
Good day, I am trying to install FFmpeg with winget tool but I am getting this error.
```
PS C:\> winget install FFmpeg
Found FFmpeg [Gyan.FFmpeg] Version 6.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
An unexpected error occurred while executing the command:
0x80070032 : The request is not supported.
```
I'm not sure if this is caused by this package or winget, but I was able to install other packages without any issue.
winget v1.2.10691
Windows 11 22H2 (22621.2134)

**Comment by GyanD** [comment]
You need at least winget v1.3

See https://devblogs.microsoft.com/commandline/windows-package-manager-1-3/#support-for-portable-packages

**Comment by dream6502** [comment]
I thought doing "winget upgrade --all" would also upgrade winget itself but I had to download updates on Microsoft store, winget is now on v1.5.2201 and I installed FFmpeg without a problem. Thanks.
