### ISSUE TITLE
AC3 audio encoding not working

### ISSUE THREAD

**Issue by jsev1x** [GyanD/codexffmpeg#104]
I've added AC3 audio tracks on many occasions in the past by copying the E-AC3 track to an AC3 track and have never had any issues.  I need to do this as my TV doesn't understand the E-AC3 format so having the extra track gives me sound on the TV.  However on the latest ffmpeg builds, the AC3 tracks are not working on my TV.  It just says the audio format is not supported.  This has not happened on previous builds even though I'm using the exact same parameters so it seems there is some error in the AC3 encoding.
It's been a while since I've updated ffmpeg (last one I was using was a build from 2021-08-18) so I don't know when this issue started occurring.

**Comment by GyanD** [comment]
You should add -report to your command and rerun with both the old version and the new one. Then open a ticket at trac.ffmpeg.org with links to both reports.
