### ISSUE TITLE
Update notifications?

### ISSUE THREAD

**Issue by nollinvoyd** [GyanD/codexffmpeg#108]
Is there a way to get notifications when updates become available? 

I have some tools, i.e. [https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx/?src=search](url), that relies on ffmpeg, but requires it to be installed manually, or at least that's the only way I know how to do it.

**Comment by GyanD** [comment]
No push notifications.

You can check and compare the .ver links e.g.

https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z.ver
https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z.ver

**Comment by pzhlkj6612** [comment]
For me, I'm watching the releases of this repository. I think this is a way to be notified when updates available. [Configuring notifications - GitHub Docs](https://docs.github.com/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications).
