### ISSUE TITLE
virus detected

### ISSUE THREAD

**Issue by dimitrinaama** [GyanD/codexffmpeg#11]
the exe files in https://github.com/GyanD/codexffmpeg/releases/tag/tools-2020-11-22-git-0066bf4d1a
are detected by 29 engines as viruses

https://www.virustotal.com/gui/file/4afa1cb974ba0d10aebb93a1e10220aa8b52c40cc57dda5461a05b807a06ae1d/detection

**Comment by deucalion** [comment]
Also see https://www.reddit.com/r/codexffmpeg/comments/its3b3/ffmpeg_windows_builds/gaatp8b/?context=3

**Comment by GyanD** [comment]
Those are false positives.

The same file hosted on my site is shown as clean.

https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-tools-2020-11-22-git-0066bf4d1a.zip

https://www.virustotal.com/gui/url/22c935f0422eb07fccfa61f3aed6eabec474656031f5a243fda2a3b44d1619b5/detection

**Comment by dimitrinaama** [comment]
hi 
https://www.virustotal.com/gui/file/4afa1cb974ba0d10aebb93a1e10220aa8b52c40cc57dda5461a05b807a06ae1d/detection

i've downloaded the file and uploaded it again to virustotal (did'nt go thru the scan url )

now it's 41 out of 64 saying it's a virus

**Comment by GyanD** [comment]
These are false positives. I don't see anything I can do about it.

**Comment by deucalion** [comment]
I believe you and I think in today's AV-landscape this is a severe issue for small software shops and opensource developers.

http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/ tells a similar tale... even 10 years ago.

Maybe (given that this is open source software) the Linux Foundation or Microsoft/Github themselves can do something about that? All I could find at the moment was https://github.community/c/software-development/47 so far (to contact Github).

Github may be able to help opensource projects by providing reproducible build facilities and automated code audits AND code-signing if the aforementioned things check out.

**Comment by GyanD** [comment]
No reports for a long time now, so closing.

**Comment by Mattwmaster58** [comment]
![image](https://github.com/GyanD/codexffmpeg/assets/26337069/434c905b-c86b-49a1-94b0-129947d86274)
Just ran into this myself today.

**Comment by GyanD** [comment]
Another false positive
