### ISSUE TITLE
Adding ffmpeg-release-essentials to WinGet

### ISSUE THREAD

**Issue by Adam-Kay** [GyanD/codexffmpeg#110]
Hello, is there a possibility of the "Essentials" build being added to WinGet - possibly under `Gyan.FFmpeg.Essentials` or something like that?

**Comment by GyanD** [comment]
Someone else shepherded the addition to Winget. You can contact them to check. See https://github.com/GyanD/codexffmpeg/issues/64

**Comment by Adam-Kay** [comment]
> Someone else shepherded the addition to Winget. You can contact them to check. See #64

Based on that post, seems like @sitiom might be the right person to bring in. 

@sitiom - What do you think of adding the "Essentials" build into WinGet?

**Comment by Adam-Kay** [comment]
Branch merged, so this can be marked as completed. Thank you both!
