### ISSUE TITLE
Cannot open transforms related files and filters.

### ISSUE THREAD

**Issue by DuckersMcQuack** [GyanD/codexffmpeg#111]
PS C:\Users\Duckers\Downloads> ffmpeg -y -i tree.mp4 -vf vidstabtransform=smoothing=20:crop=black:zoom=-15:optzoom=0:interpol=linear,unsharp=5:5:0.8:3:3:0.4 out.mp4
ffmpeg version 6.1-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tree.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : 1476248566259058
    encoder         : Lavf59.27.100
  Duration: 00:00:06.80, start: 0.000000, bitrate: 2908 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt470bg/smpte170m, progressive), 720x1280, 2954 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 h264_fbv
  Stream #0:1[0x2](und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[Parsed_vidstabtransform_0 @ 0000026efb82e180] Video transformation/stabilization settings (pass 2/2):
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     input     = transforms.trf
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     smoothing = 20
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     optalgo   = gauss
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     maxshift  = -1
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     maxangle  = -1.000000
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     crop      = Black
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     relative  = True
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     invert    = False
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     zoom      = -15.000000
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     optzoom   = Off (0)
[Parsed_vidstabtransform_0 @ 0000026efb82e180]     interpol  = Linear (1)
[Parsed_vidstabtransform_0 @ 0000026efb82e180] cannot open input file transforms.trf
[Parsed_vidstabtransform_0 @ 0000026efb82e180] Failed to configure input pad on Parsed_vidstabtransform_0
[vf#0:0 @ 0000026ef7e39780] Error reinitializing filters!
Failed to inject frame into filter network: No such file or directory
Error while filtering: No such file or directory
[out#0/mp4 @ 0000026ef7e33a80] Nothing was written into output file, because at least one of its streams received no packets.

**Comment by GyanD** [comment]
Did you run the first stage command?
