### ISSUE TITLE
Scaling filter `scale_npp` is not available in published builds

### ISSUE THREAD

**Issue by DrEsteban** [GyanD/codexffmpeg#112]
`scale_npp` apparently has more capability than `scale_cuda`. It would be great if these published builds included this scaling filter.

https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html

**Comment by GyanD** [comment]
scale_npp requires libnpp which has a nonfree license i.e. builds containing it cannot be legally redistributed. You'll need to compile it yourself - you can see if https://github.com/m-ab-s/media-autobuild_suite works for you.
