### ISSUE TITLE
option -user-agent not does not work

### ISSUE THREAD

**Issue by diamond-info** [GyanD/codexffmpeg#113]
I tried changing the `-user-agentent` option to insert my ID from the latest chrome browser: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
but I get an error in the form of text `'-user-agent' ...Unrecognized option 'user-agent'`  if I use the option: `-headers User-Agent: "Mozilla/...."`  then in my log I see that ffmpeg continues to use the default settings:
```
User-Agent: Lavf/60.16.100
Accept: */*
Range: bytes=0-
Connection: close
Host: flashvideo.rferl.org
Icy-MetaData: 1
```
Thus, this parameter has no effect. I found a similar problem here https://trac.ffmpeg.org/ticket/1291 and it says that it has been successfully solved in the new version. I was testing on the latest build of version 6.1.1 for Windows.

**Comment by GyanD** [comment]
The option name is `-user_agent`

**Comment by diamond-info** [comment]
Oh yes, I'm sorry, this parameter does not cause an error, but the log response shows that the built-in identifier is still being used:
```
User-Agent: Lavf/60.16.100
Accept: */*
Range: bytes=0-
Connection: close
Host: flashvideo.rferl.org
Icy-MetaData: 1
```

**Comment by GyanD** [comment]
This is better handled at the ffmpeg bug tracker @ trac.ffmpeg.org
