### ISSUE TITLE
[Request] Enable new d3d12va decoders

### ISSUE THREAD

**Issue by oscarbg** [GyanD/codexffmpeg#117]
Hi,
FFMPEG main branch supports D3D12VA since december.. plase can add that to full build in addition to existing D3D11VA decoders?

>ffmpeg -hwaccel d3d12va -i c:\av1\sample.mp4 -f null -

log:

> Device creation failed: -12.
> [vist#0:0/av1 @ 00000235a67716c0] [dec:libdav1d @ 00000235a676df80] No device available for decoder: device type d3d12va needed for codec libdav1d.

EDIT: testing with -hwaccel d3d13va (doesn't exist) reveals d3d11va missing from list:

>[vist#0:0/h264 @ 000001a2282bedc0] Unrecognized hwaccel: d3d13va.
>[vist#0:0/h264 @ 000001a2282bedc0] Supported hwaccels: cuda vaapi dxva2 qsv d3d11va opencl vulkan

EDIT 2: I made a equal request to Btbn:
https://github.com/BtbN/FFmpeg-Builds/issues/355
thanks..

**Comment by GyanD** [comment]
I'll look into this soon.

**Comment by GyanD** [comment]
Added to 2024-03-28 builds.

**Comment by oscarbg** [comment]
also works nice!
