### ISSUE TITLE
[Request] enable VAAPI decoders (like in BtbN Windows builds)

### ISSUE THREAD

**Issue by oscarbg** [GyanD/codexffmpeg#118]
Hi,
VAAPI supports Windows for a year at least..
FFMPEG main branch supports VAAPI Windows also for a while.. plase can add that to full build in addition to existing D3D11VA decoders?

also testing with -hwaccel d3d13va (doesn't exist) reveals vaapi missing from list:

>[vist#0:0/h264 @ 0000022b09d3ccc0] Unrecognized hwaccel: d3d13va.
>[vist#0:0/h264 @ 0000022b09d3ccc0] Supported hwaccels: cuda dxva2 qsv d3d11va opencl vulkan

seems BtbN include it:
>[vist#0:0/h264 @ 000001a2282bedc0] Unrecognized hwaccel: d3d13va.
>[vist#0:0/h264 @ 000001a2282bedc0] Supported hwaccels: cuda vaapi dxva2 qsv d3d11va opencl vulkan

thanks..

**Comment by GyanD** [comment]
I took a look at the BtbN commit which added vaapi on windows and it says doesn't actually work - it crashes.

**Comment by oscarbg** [comment]
not really working for me! but you have to have a working libva-win32 installation:
extract libva-win32 libva and vaon12_drv_video.dll dlls from:
https://www.nuget.org/packages/Microsoft.Direct3D.VideoAccelerationCompatibilityPack/1.0.2
and check with vainfo tool output like this:

Trying display: win32
libva info: VA-API version 1.21.0
libva info: Trying to open ./\vaon12_drv_video.dll
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.21 (libva 2.21.0)
vainfo: Driver version: Mesa Gallium driver 24.1.0-devel for D3D12 (NVIDIA GeForce RTX 3070)
vainfo: Supported profile and entrypoints

**Comment by GyanD** [comment]
The vaapi-linked build gets generated but with vainfo I get

```
$ ./vainfo.exe
Trying display: win32
libva info: VA-API version 1.19.0
libva info: Trying to open D:/a/_work/1/a/installdir/bin\vaon12_drv_video.dll
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

vaon12_drv_video.dll is in PWD.

**Comment by GyanD** [comment]
added to 2024-03-28 builds.

**Comment by oscarbg** [comment]
works nice! thanks..
