### ISSUE TITLE
Hello friend! Can you please help me to compile Windows executables?

### ISSUE THREAD

**Issue by zhouxinghong** [GyanD/codexffmpeg#119]
Hello friend! Can you please help me to compile Windows executables?
Just compiling Windows x64 is fine, thank you very much.🎉😜👍👏
Here is the source code address:
https://github.com/librempeg/librempeg

Because I need a latest version of librempeg Windows executable, but I can't compile it myself, so I'd like to ask you to help me build it 😜 Thank you very, very much indeed! 💗💗

**Comment by GyanD** [comment]
Try https://github.com/m-ab-s/media-autobuild_suite

You can point to a custom repo in place of stock ffmpeg.

**Comment by zhouxinghong** [comment]
Thank you very much, teacher, for your enthusiastic guidance! 👍😜💗 This tool is very good, but I am not a programmer, so I am still not able to use it.

**Comment by richardpl** [comment]
I might put lavfi-preview builds with librempeg libs soon (via github). Might do also mpv fork build too but later.

**Comment by GyanD** [comment]
@zhouxinghong you don't need to be a programmer - it is an autobuild script.  Download and extract it, then during first run of the bat file, pay attention to the message about ffmpeg source path.

@richardpl do mention a changelog noting the differences with stock ffmpeg.

**Comment by zhouxinghong** [comment]
@GyanD Thank you for your careful guidance! I read the tutorial and found that my PC is running low on disk space.😂

**Comment by zhouxinghong** [comment]
[media-autobuild_suite](https://github.com/m-ab-s/media-autobuild_suite) This library is not included [librempeg](https://github.com/librempeg/librempeg)

**Comment by GyanD** [comment]
You have to change the ffmpeg source path to librempeg as shown during first run of bat.

**Comment by zhouxinghong** [comment]
I tried, waiting for hours but no success. . .😂

**Comment by zhouxinghong** [comment]
If I make it one day, I don't know if it will work. . .

**Comment by zhouxinghong** [comment]
Many thanks to the teachers for their help! You guys are really cool 🎉💗🏆👏🍦👍😜

**Comment by zhouxinghong** [comment]
@likecrazy1 If it gets built, please let me know, thank you very much!

**Comment by richardpl** [comment]
Certainly you ask on wrong places - unrelated projects about another project release executable.

**Comment by zhouxinghong** [comment]
@richardpl Teacher, according to the audio you provided last time, you said that you need the latest librempeg, but we cannot obtain the latest librempeg executable file for Windows 10

**Comment by richardpl** [comment]
Stop spamming unrelated projects with librempeg questions/request.

**Comment by zhouxinghong** [comment]
OK!
