### ISSUE TITLE
EVC decoder is missing from latest release branch 7.0 and git branch build for windows. 

### ISSUE THREAD

**Issue by DeltaCoding0** [GyanD/codexffmpeg#123]
Even though website (https://www.gyan.dev/ffmpeg/builds/#changelog) 

changelog listed both encoder and decoder included with the full build. **Only encoder is available**. I tried "ffmpeg -decoders|grep libxevd" but it shows nothing

**Comment by GyanD** [comment]
The decoder is simply `evc`
