### ISSUE TITLE
Compile C++ using /GS option

### ISSUE THREAD

**Issue by GintV** [GyanD/codexffmpeg#129]
We're using ffmpeg.exe from this repository's releases, but it seems that it is missing some secure flags. Compiling with /GS option will harden C++ code against stack attacks.

https://learn.microsoft.com/en-us/cpp/build/reference/gs-buffer-security-check?view=msvc-160&%3BviewFallbackFrom=vs-2019

**Comment by GyanD** [comment]
I don't compile with MSVC but gcc, so /GS is not applicable.

I have source fortification and stack protection enabled but let me recheck that.

**Comment by GyanD** [comment]
Switched to `fstack-protector-strong`

**Comment by GintV** [comment]
When we can expect a new build with the new compile flag defined?

**Comment by GyanD** [comment]
Happened starting with the 25th April git build.
