### ISSUE TITLE
I can't run -stats_period when compiling for Windows. Could you add?

### ISSUE THREAD

**Issue by Thiagobhmg** [GyanD/codexffmpeg#13]
I am using -pregress to get the current frame that is being processed, leaving it in a .txt file, but I would like to use -stats_period to control the time that the file is updated. However, when adding -stats_period to the script, it presents an error message:

Unrecognized option 'stats_period'. Error splitting the argument list: Option not found

**Comment by Thiagobhmg** [comment]
sorry, just now I understand that it is not really available in the windows compilation that you make available. Could you tell me if there is a forecast to be added in the next review?

**Comment by GyanD** [comment]
It's in the git build, not the 4.3.1 release.
