### ISSUE TITLE
need to trap no video packets and audio in udp and exit ffmpg

### ISSUE THREAD

**Issue by ansariatif** [GyanD/codexffmpeg#131]
hi gyan,

there are scenario,  i capture file in segment  from udp stream cumming from ird . when stop channel from  ird setting  udp ip comming . it has only information but no audio video packet. at that case i want exit my ffmpeg process. when i send ctrl+c from from my C# program it not exit . please help me to trap this and exit ffmpeg gracefully . if i do forcefully exit ffmpeg process then file is corrupt.     

![image](https://github.com/GyanD/codexffmpeg/assets/13900715/dce3362c-478a-4bd9-b778-d2bc4cff9861)

**Comment by GyanD** [comment]
Not a general support forum. Try the [subreddit](https://www.reddit.com/r/ffmpeg/).
