### ISSUE TITLE
Format conversion error

### ISSUE THREAD

**Issue by gulangyushaonian** [GyanD/codexffmpeg#132]
When converting files to music, when converting kgm to mp3, the following error message appears. Please check it out. Thanks
PS:The file exists.
Error opening input: Invalid data found when processing input
Error opening input file G.E.M. 邓紫棋 - 天空没有极限.kgm.
Error opening input files: Invalid data found when processing input

**Comment by GyanD** [comment]
kgm does not appear to be a format that ffmpeg supports. Try the ffmpeg [subreddit](https://www.reddit.com/r/ffmpeg/).
