### ISSUE TITLE
Windows ARM builds?

### ISSUE THREAD

**Issue by mgenware** [GyanD/codexffmpeg#135]
With more and more Snapdragon X Elite laptops being released by OEMs, it would be great if Windows ARM builds are also provided.

**Comment by SebastianGode** [comment]
We really need to have an ARM64 build now. A lot of laptops with Snapdragons are shipping right now.

**Comment by GyanD** [comment]
As I mentioned in the earlier issue, I don't have a setup to natively build and test ARM binaries. Once supply/demand attains a critical mass, I'll look into it. Closed for now.

**Comment by m4heshd** [comment]
@GyanD FYI, you can now use the [`windows-11-arm`](https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/) runner.
