### ISSUE TITLE
Please share the basic theory for audio mixing from 2 channels into mono

### ISSUE THREAD

**Issue by Meterwalon** [GyanD/codexffmpeg#138]
Here were some issues during resampling the audio using swr_convert def, we found the value of waveform is a bit higher than the result using librosa-python. But also the channel-mixed method is importance to keep it. So could someone share the basic code for the part of channels mixing? We located the def under the ./FFmpeg-master/libswresample/x86/rematrix_template.c, seemed as:
`
out[i] = R(coeff1*in1[i] + coeff2*in2[i]);
`
seem like the wieghts were both float 1.0 to calculate the rematrix element, but we check the result that was higher than normal. was it any noise shaping method still implemented?
:)
thanks a lot

**Comment by GyanD** [comment]
Queries related to ffmpeg source should be posted to ffmpeg-user mailing list.
