### ISSUE TITLE
mkv to png color error

### ISSUE THREAD

**Issue by kniriaM** [GyanD/codexffmpeg#139]
When using the command: "ffmpeg -i D:\entry.mkv -qscale:v 1 -qmin 1 -qmax 1  -fps_mode passthrough D:\tmp_frames\frame%08d.png" to break the video frames, the colors and black tones are altered in the PNG. This does not occur in JPG when using "-color_trc gamma28," but no extra command corrects this in PNG. I am using version "ffmpeg version 2024-06-03-git-77ad449911-full_build-www.gyan.dev".

**Comment by GyanD** [comment]
Usage questions belong on https://video.stackexchange.com/ or https://www.reddit.com/r/ffmpeg/

**Comment by kniriaM** [comment]
> Usage questions belong on https://video.stackexchange.com/ or https://www.reddit.com/r/ffmpeg/

Sorry, but that wasn't a question. This error occurs only on the Windows platform and has no solution. The only method that "fixes" the problem is switching to the Linux platform, where the color error does not occur. There is something wrong with the transformation from MKV to PNG on last build Windows 11.

**Comment by GyanD** [comment]
The code does not differ across platforms. It can differ across versions as can playback fidelity or rendering defaults. In any case, this can be troubleshooted at one of the forums linked above, not here.
