### ISSUE TITLE
-vf mpdecimate,setpts=N/FRAME_RATE/TB frame rate not detected 7.0.x

### ISSUE THREAD

**Issue by ruboard** [GyanD/codexffmpeg#140]
-vf mpdecimate,setpts=N/FRAME_RATE/TB frame rate not detected 7.0.x
No information about the input framerate is available. Falling back to a default value
of 25fps. Use the -r option if you want a different framerate.

the input file is the most common h264, full metadata .30fps
ffmpeg 6.x as it should, the frame rate is determined automatically!

**Comment by GyanD** [comment]
There was a change made to setpts filter so it no longer relays the input framerate. If you add `-fps_mode passthrough` the timestamps set by setpts won't get altered.

You can open a ticket at trac.ffmpeg.org if you want to ask to restore the old behaviour.

**Comment by ruboard** [comment]
Thank you. I checked. It works.
**Now it should look like this, right ?**: `-vf mpdecimate,setpts=N/FRAME_RATE/TB -fps_mode passthrough`

7.x is just a big commotion. There is clearly a lack of information about command changes. It's all surprises!
**Could you please provide a link with a complete list of changes specifically for commands (v6.1.1 vs 7.0) ?**

**Comment by GyanD** [comment]
ffmpeg has hundreds of components - there's no comprehensive list of all changes with implications for command-line users.
