### ISSUE TITLE
problem in screen recording in window 11.

### ISSUE THREAD

**Issue by Santoshpatel112** [GyanD/codexffmpeg#142]
![screenrecoding](https://github.com/GyanD/codexffmpeg/assets/134463761/f7a50561-e23e-4824-a333-6a9a934f719d)

code ->>ffmpeg -f gdigrab -framerate 30 -i desktop recoding.mp4

**Comment by GyanD** [comment]
Works here.

You don't appear to be using ffmpeg directly. Which software are you using?

**Comment by Santoshpatel112** [comment]
am not understading like software if any software then plz suggest 
(am just working with command promt ffmpeg library link with our envirnment varible and use normaly)
then i see screen recodring does not open ??
*****
sir i need to some help by you am intrested this org..

**Comment by GyanD** [comment]
General ffmpeg troubleshooting and queries should be posted to [subreddit](https://www.reddit.com/r/ffmpeg/)
