### ISSUE TITLE
ffmpeg build with libx265; incompatible pointer type

### ISSUE THREAD

**Issue by hydra3333** [GyanD/codexffmpeg#146]
EDIT: oops sorry this is probably posted in the wrong place ?

Hi, have you noticed this over at MABS ?
https://github.com/m-ab-s/media-autobuild_suite/issues/2750
I'm not sure if you're seeing the same thing in your ffmpeg builds ... if not it would be surprising to me given how generic MABS build system is.
Cheers

Oh dear, looks like something is currently broken/incompatible over at ffmpeg ?
I guess all we can do is wait.

Fresh build:

00:18:18 ├ Compiling FFmpeg with Vapoursynth R68
00:18:18 ├ FFmpeg will need vapoursynth.dll and vsscript.dll to run using vapoursynth demuxers!
00:18:19 Running git clone for ffmpeg...
00:20:06 Running git update for ffmpeg...
00:20:09 ┌ ffmpeg git ............................... [Recently updated]
00:20:10 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
00:20:21 ├ Compiling static FFmpeg...
00:20:22 ├ Running configure...
00:25:23 ├ Running make...
Likely error (tail of the failed operation logfile):
AR libavfilter/libavfilter.a
CC libavcodec/libx265.o
src/libavcodec/libx265.c: In function 'libx265_encode_frame':
src/libavcodec/libx265.c:802:59: error: passing argument 5 of 'ctx->api->encoder_encode' from incompatible pointer type [-Wincompatible-pointer-types]
802 | pic ? &x265pic : NULL, &x265pic_out);
| ^~~~~~~~~~~~
| |
| x265_picture *
src/libavcodec/libx265.c:802:59: note: expected 'x265_picture **' but argument is of type 'x265_picture *'
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/libx265.o] Error 1
make failed. Check C:/MABS/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
00:28:17 Creating diagnostics file...

Attach C:\MABS\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by GyanD** [comment]
My MABS hasn't been run since that change in x265.

This is the offending commit: https://bitbucket.org/multicoreware/x265_git/commits/c69c113960834400545bc4bce2830ff51dcb86b3

You can pin to https://bitbucket.org/multicoreware/x265_git/commits/3d808f14db2ea026604ee88bc5012c842de61d0e

The references to the received packet need to be updated in lavc.

**Comment by GyanD** [comment]
Fixed in https://github.com/FFmpeg/FFmpeg/commit/1f801dfdb5066aadf0ade9cb5e94d620f33eacdc
