### ISSUE TITLE
ffmpeg 7.02 crash randomly with Exception code: 0xc0000005 or Exception code: 0xc000008f

### ISSUE THREAD

**Issue by ansariatif** [GyanD/codexffmpeg#148]
hi gyan,

my application uses ffmpeg for 24x7 file capture. after  last window update ffmpeg crashed randomly with  Exception code: 0xc0000005 or Exception code: 0xc000008f in both windows 10 and windows 11. 

### windows exception

Faulting application name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000008f
Fault offset: 0x0000000001dc0d55
Faulting process id: 0x49c8
Faulting application start time: 0x01daf3ec7d8a85f7
Faulting application path: D:\Logger_win\config\ffmpeg.exe
Faulting module path: D:\Logger_win\config\ffmpeg.exe
Report Id: 889bab2a-85e3-4394-a15a-d2442a692b84

Faulting application name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.19041.4522, time stamp: 0x8a1bb6f3
Exception code: 0xc0000005
Fault offset: 0x00000000000649f6
Faulting process id: 0x4378
Faulting application start time: 0x01daf3ce2e9e9849
Faulting application path: D:\Logger_win\config\ffmpeg.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: fd1bbe87-6591-4d6a-b904-48ec9cc72ff6
Faulting package full name: 

Faulting application name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.19041.4522, time stamp: 0x8a1bb6f3
Exception code: 0xc0000025
Fault offset: 0x00000000001025e6
Faulting process id: 0x30d0
Faulting application start time: 0x01daf3d138bd0b6b
Faulting application path: D:\Logger_win\config\ffmpeg.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: ff99e787-cfa9-475d-b722-44af47a51359
Faulting package full name: 

please help me. provide resolution

**Comment by GyanD** [comment]
Needs details. Full command used + debug level log. OS info.

**Comment by Templayer** [comment]
Win7

![image](https://github.com/user-attachments/assets/970d0200-9e07-4ce4-ab64-f2b98a52781e)

**Comment by Templayer** [comment]
> Win7
> 
> ![image](https://private-user-images.githubusercontent.com/11728067/365666038-970d0200-9e07-4ce4-ab64-f2b98a52781e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODgzMzUsIm5iZiI6MTcyNTg4ODAzNSwicGF0aCI6Ii8xMTcyODA2Ny8zNjU2NjYwMzgtOTcwZDAyMDAtOWUwNy00Y2U0LWFiNjQtZjJiOThhNTI3ODFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEzMjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1M2ZmYWY2MWNlYzY2ZmNhNjJjNWI2NmUyNDIxMDEyODJiNjZlOWNkZjVkOTIxYjM3YjRhNzY2MzAzMWQ3MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FwAum4h6ekzDuhBbhaBmLSVaoQT1HMRE0vYSjfAbEeI)

Nevermind, I took a look at the main site and it said that the full builds are no longer supported for Win7.

So I made it work using VxKex.

![image](https://github.com/user-attachments/assets/2ad50aa2-e860-4200-95cb-4d6a7ca44080)

**Comment by alcrus** [comment]
0xc0000005 is not related to Win 7. Have same problem, it's always crashing silently on HEVC encoding, Windows 11, i9 14900K, sometimes after a few minutes, sometimes after hours of encoding.

-report option doesn't show any additional information.

Switched to BtbN ffmpeg builds and all problems are gone.
The only difference I see is gcc 13.2.0 - MSYS2 vs gcc 14.2.0 - crosstool.
Can be one more gcc 13.2.0 optimization bug...

**Comment by Templayer** [comment]
> 0xc0000005 is not related to Win 7. 

That statement is false. For Win7, that error is thrown at the application launch. For you, the error is intermediary (AFTER it launches and is doing stuff).

So while there might be a connection between them, unless otherwise proven, your 0xc0000005 and mine 0xc0000005 are two different errors.

**Comment by aleksei-z** [comment]
Whatever. Bug was opened for random crashes on Windows 10 and 11.

**Comment by GyanD** [comment]
> 0xc0000005 is not related to Win 7. Have same problem, it's always crashing silently on HEVC encoding, Windows 11, i9 14900K, sometimes after a few minutes, sometimes after hours of encoding.
> 
> Command used: ffmpeg -y -i video.mov -max_muxing_queue_size 1024 -filter_complex "[0:0]crop=1920:800:0:140[v]" -map "[v]" -c:v libx265 -pix_fmt yuv420p10le -x265-params "aq-mode=3:repeat-headers=0:strong-intra-smoothing=1:bframes=4:b-adapt=2:frame-threads=0:colormatrix=bt709:hdr10_opt=0:hdr10=0" -crf:v 18 -preset:v slow -map_metadata -1 -map_chapters 0 -default_mode infer_no_subs encoded.mkv

Which build and version?

**Comment by aleksei-z** [comment]
The last build I tested was ffmpeg-2024-09-19-git-0d5b68c27c-full_build.7z but the same happens with all builds I tried in the last ~2 months, including latest 7.0.2 release build.

**Comment by GyanD** [comment]
Does it happen if you reduce bframes to 2?

**Comment by aleksei-z** [comment]
Yes, it still happens. Log attached

Faulting application name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x66ebfd32
Faulting module name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x66ebfd32
Exception code: 0xc0000005
Fault offset: 0x0000000005eb71b9
Faulting process id: 0xAB4C
Faulting application start time: 0x1DB107B8239AA77
Faulting application path: G:\Src\ffmpeg\bin-git\ffmpeg.exe
Faulting module path: G:\Src\ffmpeg\bin-git\ffmpeg.exe
Report Id: 3969d75d-5271-45bc-84bd-81e6d16f73c4
Faulting package full name: 
Faulting package-relative application ID: 

[ffmpeg-20240926-182058.zip](https://github.com/user-attachments/files/17159220/ffmpeg-20240926-182058.zip)

**Comment by aleksei-z** [comment]
One more. In this case that's svtav1 encoding, same 0xc0000005 exception.

G:\Src\ffmpeg\bin-git\ffmpeg.exe -report -y -i 01-.mkv   -max_muxing_queue_size 1024    -filter_complex "[0:0]crop=1920:1040:0:20[v]" -map "[v]"  -c:v libsvtav1 -pix_fmt yuv420p10le     -strict experimental -preset 4 -color_primaries bt709 -color_trc bt709 -colorspace bt709  -svtav1-params "tune=0:film-grain-denoise=0:tile-columns=0:tile-rows=0:scd=0"  -crf 14   -map_metadata -1 -map_chapters 0   -default_mode infer_no_subs  encoded-01-.mkv

Faulting application name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x66ebfd32
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000fffffff3
Faulting process id: 0x7148
Faulting application start time: 0x1DB10AAB49D982B
Faulting application path: G:\Src\ffmpeg\bin-git\ffmpeg.exe
Faulting module path: unknown
Report Id: d9e177ec-9c0f-48cd-9d2f-f595a50bbe41
Faulting package full name: 

[ffmpeg-20240926-235849.zip](https://github.com/user-attachments/files/17167921/ffmpeg-20240926-235849.zip)

**Comment by GyanD** [comment]
Does it happen with 7.1?

**Comment by aleksei-z** [comment]
Now I got 0xc0000094 and 0xc0000005

Faulting application name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x66fa894f
Faulting module name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x66fa894f
Exception code: 0xc0000094
Fault offset: 0x0000000006250acb
Faulting process id: 0xF45C
Faulting application start time: 0x1DB1375F16E0076
Faulting application path: G:\Src\ffmpeg\bin-7.1\ffmpeg.exe
Faulting module path: G:\Src\ffmpeg\bin-7.1\ffmpeg.exe
Report Id: 76b6cff0-3cb9-4928-89b9-be793650eafa
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x66fa894f
Faulting module name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x66fa894f
Exception code: 0xc0000005
Fault offset: 0x0000000005fc70b9
Faulting process id: 0x12A4C
Faulting application start time: 0x1DB13BBEDF39A83
Faulting application path: G:\Src\ffmpeg\bin-7.1\ffmpeg.exe
Faulting module path: G:\Src\ffmpeg\bin-7.1\ffmpeg.exe
Report Id: 7a57dcd8-197e-4080-a3c5-d23933e790ea
Faulting package full name: 
Faulting package-relative application ID:

**Comment by GyanD** [comment]
Someone's reported a crash with the same [exception code](https://trac.ffmpeg.org/ticket/11237) with a BtbN build (gcc 14.2.0) . Since no one's reported it (yet) with an essentials build, I suspect some change in an external library.

For proper debugging, I'll need a minimal reproducible command (and assets, if it matters).

**Comment by aleksei-z** [comment]
Testing both builds on new ASUS BIOS with "Intel microcode update 0x12B for its 13th and 14th generation Core processors, addressing persistent stability issues stemming from voltage irregularities". Will let you know about results.

**Comment by aleksei-z** [comment]
5 days of testing, no any crashes so far, So it looks like in my case it was unstable CPU.

**Comment by Templayer** [comment]
> 5 days of testing, no any crashes so far, So it looks like in my case it was unstable CPU.

Got to love those Intels, right? :P
