### ISSUE TITLE
winget install with --scope machine has the wrong permissions

### ISSUE THREAD

**Issue by heitbaum** [GyanD/codexffmpeg#149]
when installing the winget package with `--scope user`, all is fine. But when installing it with `--scope machine` the permissions on the directory does not allow users to use the binaries.

This is the `C:\Program Files\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-7.0.1-full_build` folder
![image](https://github.com/user-attachments/assets/8d8fa4fa-f2c1-43b8-82e2-5f04edba2e5e)
 
This is the `C:\Program Files\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe` folder
![image](https://github.com/user-attachments/assets/8cb9da98-ad56-4ce3-bf05-40a3b946394c)

**Comment by GyanD** [comment]
This looks like a Winget issue - ffmpeg is just a passive payload. Try https://github.com/microsoft/winget-pkgs/issues
