### ISSUE TITLE
FDK-AAC

### ISSUE THREAD

**Issue by fcore117** [GyanD/codexffmpeg#15]
Please include this very essential library and if you fear patents then include as downloadable .dll like someone in oss.netfarm.it does this. AAC if future of audio codecs especially for commercial players and it is very essential part.

![image](https://user-images.githubusercontent.com/1313813/109801938-d855c300-7c27-11eb-9152-1629fb107ee0.png)

**Comment by GyanD** [comment]
FFmpeg builds linking to libfdk-aac are not distributable. The netfarm builds appear to have modified ffmpeg's configure to produce a GPL v3 build with libfdk-aac.

**Comment by fcore117** [comment]
Maybe do same way? anyway at least there are Netfarm builds as FFmpeg own AAC is still not par with FDK. Maybe one day in far future FFmpeg has superior AAC encoder like x264 and x265 are hi-end quality encoders. Bye.

**Comment by 89z** [comment]
https://github.com/GyanD/codexffmpeg/issues/18
