### ISSUE TITLE
FFmpeg 6.1.2 has been released

### ISSUE THREAD

**Issue by Dobypeti** [GyanD/codexffmpeg#151]
Hello,

I just want to note that FFmpeg 6.1.2 has been released (https://github.com/FFmpeg/FFmpeg/commit/b1a4534186ca51b0457579fc05a5739eb2cc45cd; https://www.ffmpeg.org/download.html#release_6.1) but the binary packages haven't yet been uploaded to the site and this repository.

Thank you for hosting binaries of FFmpeg.

**Comment by GyanD** [comment]
Only new tags on the latest release branch (currently 7.0) lead to a new release build.
