### ISSUE TITLE
[Question] Difference Between "Full Build" and "Full Build Shared"?

### ISSUE THREAD

**Issue by 03302024** [GyanD/codexffmpeg#155]
What is the practical difference between "Full Build" and "Full Build Shared"? I can see ffmpeg.exe and ffplay.exe and ffprobe.exe have diffent sizes, and the "Shared" version have some dll files extra.

**Comment by GyanD** [comment]
In the shared build, the libraries which are part of the FFmpeg project are individual files. This format is meant for software developers who wish to integrate these libraries into their own applications.

If you're an end user, it should make no difference to you. Only thing to be mindful of is that if you have multiple installations of shared ffmpeg builds in your PATH, then the EXEs here may try to load those other DLLs which can lead to a crash or failure.

**Comment by 03302024** [comment]
Thank you for the explanations. 

So, if an app uses ffmpeg.exe, then there would be no problem if one uses the shared version, as (the smaller sized) ffmpeg.exe would load the dlls as needed, right?

If that is correct, I will always use the shared version then. Some apps are picky, like Audacity which looks for a dll file that is present in the shared version.

**Comment by pzhlkj6612** [comment]
> If that is correct, I will always use the shared version then. Some apps are picky, like Audacity which looks for a dll file that is present in the shared version.

Maybe you mixed the DLLs of ffmpeg and Audacity? How Audacity searches DLL has nothing to do with how ffmpeg does so.

**Comment by 03302024** [comment]
Audacity uses ffmpeg for audio file extensions like aac. In Audacity preferences, you need to point it to the location of ffmpeg files.

**Comment by pzhlkj6612** [comment]
> In Audacity preferences, you need to point it to the location of ffmpeg files.

Thanks, now I get it. You indeed need those shared builds.

I've also found this official docs: [Installing FFmpeg | Audacity Support](https://support.audacityteam.org/basics/downloading-and-installing-audacity/installing-ffmpeg).

**Comment by 03302024** [comment]
> I've also found this official docs: [Installing FFmpeg | Audacity Support](https://support.audacityteam.org/basics/downloading-and-installing-audacity/installing-ffmpeg).

But, the question is not about Audacity. The question is:

> So, if an app uses ffmpeg.exe, then there would be no problem if one uses the shared version, as (the smaller sized) ffmpeg.exe would load the dlls as needed (without editing Windows path), right?

**Comment by pzhlkj6612** [comment]
> The question is:
> 
> > So, if an app uses ffmpeg.exe, then there would be no problem if one uses the shared version, as (the smaller sized) ffmpeg.exe would load the dlls as needed (without editing Windows path), right?

Right.

However, you should not modify the file structure, otherwise the ffmpeg executable may not be able to find its dependencies. For example, in the "ffmpeg-7.1-full_build-shared" directory, all DLL and EXE files are in the same "bin" directory:

```console
> tree /A /F .
...
FFMPEG-7.1-FULL_BUILD-SHARED
|   LICENSE
|   README.txt
|
+---bin
|       avcodec-61.dll
|       avdevice-61.dll
|       avfilter-10.dll
|       avformat-61.dll
|       avutil-59.dll
|       ffmpeg.exe
|       ffplay.exe
|       ffprobe.exe
|       postproc-58.dll
|       swresample-5.dll
|       swscale-8.dll
|
...

```

.

**Comment by 03302024** [comment]
Very good, thank you.
