### ISSUE TITLE
.ARW file ffprobe 

### ISSUE THREAD

**Issue by lossless-debug** [GyanD/codexffmpeg#157]
[tiff @ 000001d585903e00] Unknown compression method 32767
[tiff_pipe @ 000001d5858dfb80] Could not find codec parameters for stream 0 (Video: tiff, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, tiff_pipe, from 'C:\0.ARW':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: tiff, none, 25 fps, 25 tbr, 25 tbn

**Comment by GyanD** [comment]
For this error. you may open an enhancement ticket at trac.ffmpeg.org. Nothing can be done in the build process.

**Comment by lossless-debug** [comment]
> For this error. you may open an enhancement ticket at trac.ffmpeg.org. Nothing can be done in the build process.

thanks for answer
