### ISSUE TITLE
libjxl update? (JPEG XL)

### ISSUE THREAD

**Issue by lossless-debug** [GyanD/codexffmpeg#158]
https://github.com/libjxl/libjxl

**Comment by GyanD** [comment]
?

**Comment by lossless-debug** [comment]
FFmpeg does not reduce file size when jpeg is compressed to jpegxl losslessly. But libjxl does. So I thought that FFmpeg uses an old version of libjxl and asked about updating.

**Comment by GyanD** [comment]
The current build uses libjxl updated till Oct 11.

General ffmpeg troubleshooting and queries should be posted to [subreddit](https://www.reddit.com/r/ffmpeg/)
