### ISSUE TITLE
libplacebo not working at all

### ISSUE THREAD

**Issue by clementiae** [GyanD/codexffmpeg#159]
Ffmpeg build: `ffmpeg-2024-10-31-git-87068b9600-full_build`

`libplacebo` doesn't work at all. Empty 0KB video file is created, but nothing is encoded. Just nothing happens. No error is yielded.

Ffmpeg build that works: `2024-10-02-git-358fdf3083-full_build`

**Comment by GyanD** [comment]
Yes, it appears broken in ffmpeg. See https://trac.ffmpeg.org/ticket/11246

**Comment by clementiae** [comment]
The issue has been fixed!
