### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by SubJunk** [GyanD/codexffmpeg#16]
Is there somewhere I can find out the versions of dependencies like libx264, fontconfig, etc.?

P.S. I am migrating from Zeranoe to this for my project https://github.com/UniversalMediaServer/UniversalMediaServer
Thank you for providing these!

**Comment by GyanD** [comment]
Usually git HEAD for most of them at time of compilation. A few like vidstab I clamp because the library has changed API/ABI but the ffmpeg wrapper hasn't.

**Comment by SubJunk** [comment]
Ok, thanks
