### ISSUE TITLE
The CUDA11.7 and FFMPEG6.1.1 versions do not match

### ISSUE THREAD

**Issue by Vleaguer** [GyanD/codexffmpeg#161]
Which FFMPEG version matches CUDA11.7?
When I encoding YUV  file(.yuv), the console displays the following error:
[h264_nvenc @ 000002faa5950d40] Driver does not support the required nvenc API version. Required: 12.1 Found: 12.0
[h264_nvenc @ 000002faa5950d40] The minimum required Nvidia driver for nvenc is (unknown) or newer

**Comment by GyanD** [comment]
You will need Nvidia driver 531.61 or newer.

**Comment by Vleaguer** [comment]
Thanks!  I've solved it！
