### ISSUE TITLE
A question about MP3 encoder

### ISSUE THREAD

**Issue by Vleaguer** [GyanD/codexffmpeg#163]
Help!
When I use AV_CODEC_ID_MP3 encoding audio stream,something wrong occured：
I try to extract audio stream(AV_CODEC_ID_AAC) and converted AV_CODEC_ID_AAC format to AV_CODEC_ID_MP3.
While running avcodec_receive_packet() to the last packet,the CMD prompt:
[libmp3lame @ 00000221ae59d800] Trying to remove 47 more samples than there are in the queue.
![clip](https://github.com/user-attachments/assets/d90a9145-e38e-4346-8039-4855e043f34e)
Thanks!

**Comment by GyanD** [comment]
Support for ffmpeg usage belongs to [the subreddit](https://www.reddit.com/r/ffmpeg/)

**Comment by Vleaguer** [comment]
Thanks！
