### ISSUE TITLE
Include LittleCMS 2 in full build

### ISSUE THREAD

**Issue by toine512** [GyanD/codexffmpeg#166]
Hi.

Thank you Gyan for those full builds that have made me happy over some years now.

The filter "iccgen" requires `--enable-lcms2`. This is a dependency that was added recently. Have you already considered adding it to the full build ?
https://github.com/mm2/Little-CMS

Mentions :
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20220419124656.121638-3-ffmpeg@haasn.xyz/
https://trac.ffmpeg.org/ticket/9672

**Comment by GyanD** [comment]
Done.

**Comment by toine512** [comment]
Thanks.
It just works.
