### ISSUE TITLE
Zawgyi Font Encoding Issue

### ISSUE THREAD

**Issue by neolinn** [GyanD/codexffmpeg#17]
I have encounter the following issue.
I am using ffmpeg version 2021-03-14-git-1d61a31497-full_build-www.gyan.dev
Myanmar font (Zawgyi Font) is missing some character when under the second line
missing characters are "​ေ" "​ြ" and such more.
How can I do these Problem.
Please guide me

**Comment by GyanD** [comment]
Font rendering is handled by the third-part freetype library.

For bug reports, go to https://www.freetype.org/developer.html#bug-report
