### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by Nexus2018** [GyanD/codexffmpeg#2]
011 2020-10-18: added frei0r plugins to full builds

Download git full with 4.3.1-2020-10-28
Run the following command for Windows:
 ffmpeg  -loglevel debug -i "D:\testa.mp4" -vf "frei0r=glow:20" -t 10 "D:\testb.mp4"

Error output:
[Parsed_frei0r_0 @ 00000289861defc0] Setting 'filter_name' to value 'glow'
[Parsed_frei0r_0 @ 00000289861defc0] Setting 'filter_params' to value '20'
[h264 @ 0000028985fa9d00] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
[Parsed_frei0r_0 @ 00000289861defc0] Looking for frei0r effect in '/usr/local/lib/frei0r-1/glow.dll'.
[Parsed_frei0r_0 @ 00000289861defc0] Looking for frei0r effect in '/usr/lib/frei0r-1/glow.dll'.
[Parsed_frei0r_0 @ 00000289861defc0] Looking for frei0r effect in '/usr/local/lib64/frei0r-1/glow.dll'.
[Parsed_frei0r_0 @ 00000289861defc0] Looking for frei0r effect in '/usr/lib64/frei0r-1/glow.dll'.
[Parsed_frei0r_0 @ 00000289861defc0] Could not find module 'glow'.
[AVFilterGraph @ 0000028985f91e80] Error initializing filter 'frei0r' with args 'glow:20'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0

Make [MPlayer](https://oss.netfarm.it/mplayer/)'s ffmpeg and frei0r not report errors,
Output:
[Parsed_frei0r_0 @ 0000020ca78684c0] Setting 'filter_name' to value 'glow'
[Parsed_frei0r_0 @ 0000020ca78684c0] Setting 'filter_params' to value '20'
[Parsed_frei0r_0 @ 0000020ca78684c0] Looking for frei0r effect in 'D:\Software\MPlayer_bak\frei0r-1\glow.dll'.
[Parsed_frei0r_0 @ 0000020ca78684c0] name:Glow author:'Richard Spindler' explanation:'Creates a Glamorous Glow' color_model:rgba8888 frei0r_version:1 version:0.1 num_params:1

**Comment by GyanD** [comment]
See the last line of the README.txt file.

**Comment by Nexus2018** [comment]
Sorry, I missed the README.txt file.

Is it possible to put frei0r folder and FFMpeg.exe in the same file, or in a specific location? It can be used without adding PATH.Make a portable version for use on other computers.

Reference [MPlayer](https://oss.netfarm.it/mplayer/) 
“FFmpeg build supports frei0r plugins that needs be to downloaded separately, I've prepared frei0r-plugins-x86-v1.7.0-7-g9d3a813.7z and frei0r-plugins-x86_64-v1.7.0-7-g9d3a813.7z. Just unpack into FFmpeg directory, you should have ffmpeg.exe and at the same level frei0r-1 subdir”

**Comment by GyanD** [comment]
No, that's due to a patch in mplayer's ffmpeg repo
