### ISSUE TITLE
Release querry still pointing to 4.3.2

### ISSUE THREAD

**Issue by VuiMuich** [GyanD/codexffmpeg#20]
Hi,
is it on purpose that the release querry file (https://www.gyan.dev/ffmpeg/builds/release-version) is still listing 4.3.2 as most recent, while the release section and github mirror are on 4.4?
I am preparing a PR for chocolatey community packages offering the full build and just stumbled over this wondering, why the update-script won't catch this..

**Comment by GyanD** [comment]
It says 4.4. Delete your cache and check, or fetch it via curl/wget..etc

**Comment by VuiMuich** [comment]
oops, you are right, sorry.
Then for some other reason the update-script doesn't catch which is the latest version.
But that's probably not on your side anymore.
Thanks for you very quick response anyways and thanks for your great work!

**Comment by GyanD** [comment]
I changed the release version string by removing the commit date, as it's not necessary for release packages.

**Comment by VuiMuich** [comment]
I never dug "that deep" into the script, just briefly scanned through it for `essential_build` references and changed them for `full_build`.
But as I am looking now at it, it appears the script is not checking for this, but extracting the version from a download-link.
I guess I might just update this script to check for your release reference now...

Just for reference, it's this update.ps1:  https://github.com/VuiMuich/chocolatey-coreteampackages/blob/b6968422f83d7bbca505a57c0ac131ce4b286dab/automatic/ffmpeg/update.ps1

**Comment by VuiMuich** [comment]
dang you are fast 😆 was just returning to close this just to see it is already
