### ISSUE TITLE
It seems that Setts Bitstream Filter is missing

### ISSUE THREAD

**Issue by Mitra-M** [GyanD/codexffmpeg#21]
(Thank you for great builds)

I can use all Bitstream Filters except `setts`.
`input -vcodec libx264 -bsf setts=pts=DTS output.mxf`  gets this error :

> Error parsing bitstream filter sequence 'setts=pts=DTS': Bitstream filter not found

I'm using the last 4.4 version.

**Comment by GyanD** [comment]
Can't reproduce here. Add -report, rerun and share report.

**Comment by Mitra-M** [comment]
Tried again , but it works perfectly now  

So sorry , It was my fault.
