### ISSUE TITLE
-pattern_type glob not supported

### ISSUE THREAD

**Issue by patton421** [GyanD/codexffmpeg#23]
I was hoping to generate an avi file using png files pattern matched using a wildcard.  

![image](https://user-images.githubusercontent.com/51868218/126574732-04ff63d8-2323-4bc6-9e4d-ef7d03036713.png)

**Comment by patton421** [comment]
Also, thanks for building these binaries!

**Comment by GyanD** [comment]
FFmpeg relies on the OS to provide globbing support. The functions it currently calls aren't supported on Windows. 

Windows does offer globbing support through [https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilea](FindFirstFile), but you'll have to open a ticket at trac.ffmpeg.org to request it.
