### ISSUE TITLE
How to reduce the dependencies on mingw's dll

### ISSUE THREAD

**Issue by steven8274** [GyanD/codexffmpeg#24]
@GyanD Thanks for supplying the built ffmpeg for Windows at first!It's very convenient!
Since I need a win32 version ffmpeg, so I try to compile it by myself.
After many attempts, I finally built a ffmpeg with mingw32.But I found the ffmpeg.exe depends on nearly all these DLLs in directoy '/mingw32/bin'.If I want to use it in 'cmd' terminal, I must copy these DLLs to the directory of ffmpeg.exe.
However, I found the version you supplied (which should is also built by'MSYS2' gcc toolchains I guess) doesn't depend on these DLLs, could you tell me how to achieve this?THANKS A LOT!

**Comment by GyanD** [comment]
Make sure your LDFLAGS env variable has `-static-libgcc -static-libstdc++` and your ffmpeg configure has `--enable-static --disable-shared --extra-ldflags=-static --pkg-config-flags=--static`

**Comment by steven8274** [comment]
Thank you very much!@GyanD
I'll try it and tell you the result.
Thanks again!

**Comment by steven8274** [comment]
@GyanD YES!That works!
Since I configure LDFLAGS env variable and set ffmpeg configure as you said, my new ffmpeg.exe never depends on those DLLs under '/mingw32/bin' directory!Thanks again for sharing this valuable experience selflessly！
