### ISSUE TITLE
How to build ffmpeg dlls to debug under Visual Studio?

### ISSUE THREAD

**Issue by steven8274** [GyanD/codexffmpeg#26]
Hi, @GyanD, I met another problem and searching on google with no good advice.
I have built ffmpeg dlls with your seggustions, and got these independent dlls.I can link these dlls in VS project with '/SAFESEH:NO' linking option.But I find these dlls can not be debuged.I try to built ffmpeg with these additional configuration 
 parameters: '--enable-debug=3 --disable-optimizations --disable-stripping', but the built dll still can not be debuged.I found these suggested building parameters on 'MediaSDK' github page: https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-FFmpeg-QSV.It suggest these parameters to build a debug ffmpeg(On ubuntu):
./configure --arch=x86_64 --disable-yasm --enable-vaapi --enable-libmfx  \
            --enable-debug=3 --disable-stripping --extra-cflags=-gstabs+ \
            --disable-optimizations
make
Among these parameters, I found '--extra-cflags=-gstabs+' is not compatible with the gcc in mingw64, so I remove it.
Could you give me some advice on how to build a debugable ffmpeg for VS debuging on Windows?Thanks in advance!

**Comment by GyanD** [comment]
Can you debug under gdb?

**Comment by steven8274** [comment]
> No experience with VS. Can you debug under gdb?

No, my programe use ffmpeg dlls can only be compiled by msvc or clang.Thanks!

**Comment by GyanD** [comment]
What's your full ffmpeg configure string?

**Comment by steven8274** [comment]
> What's your full ffmpeg configure string?

My configure string is:
../../configure --enable-shared --enable-libmfx --enable-encoder=h264_qsv --enable-decoder=h264_qsv --enable-gpl --enable-libx264 --extra-ldflags=-static --pkg-config-flags=--static --prefix=../../build/mingw64

Besides, I set 'LDFLAGS' as:
export LDFLAGS="-static-libgcc -static-libstdc++ "

**Comment by GyanD** [comment]
If you're building ffmpeg using msvc, you should add `--toolchain=msvc`. Also, see https://trac.ffmpeg.org/wiki/CompilationGuide/MSVC

**Comment by steven8274** [comment]
I had read that post.I know these steps to build a ffmpeg with msvc with default configuration.But I want to build a ffmpeg with Intel, NVIDIA and AMD video card hardware codec ablitities, not only the default configuration.So besides ffmpeg, I should build 'libmfx', 'NVIDIA Video Codec SDK' and 'libamf' also.These SDKs can be built with msvc?How to build them?
