### ISSUE TITLE
HTTPS to HTTP redirect causes issue with PowerShell

### ISSUE THREAD

**Issue by zmwangx** [GyanD/codexffmpeg#3]
First of all thanks for carrying the torch of offering FFmpeg Windows builds. I use your builds in CI tests for my FFmpeg Rust binding: https://github.com/zmwangx/rust-ffmpeg. Really helpful for a non-Windows guy like me.

That said, there's a small problem: the non-versioned URLs redirect from HTTPS to HTTP, then back to HTTPS:

```console
$ curl -LI https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
HTTP/1.1 200 Connection established

HTTP/2 303
date: Tue, 03 Nov 2020 08:54:06 GMT
server: Apache
location: http://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.1-2020-10-28-full_build-shared.7z
content-type: text/html; charset=iso-8859-1
via: e4s

HTTP/1.1 301 Moved Permanently
Date: Tue, 03 Nov 2020 08:54:07 GMT
Server: Apache
Location: https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.1-2020-10-28-full_build-shared.7z
Content-Type: text/html; charset=iso-8859-1

HTTP/2 200
date: Tue, 03 Nov 2020 08:05:02 GMT
server: Apache
last-modified: Sun, 01 Nov 2020 10:38:40 GMT
etag: "2596381-5b3093baf87ca"
accept-ranges: bytes
content-length: 39412609
age: 2945
via: e4s
content-type: application/x-7z-compressed
```

The HTTPS -> HTTP redirect causes a non-recoverable failure in PowerShell:

```console
> Invoke-WebRequest https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
Invoke-WebRequest:
303 See Other
See Other
The answer to your request is located here.
```

More details about the PowerShell issue here: https://github.com/PowerShell/PowerShell/issues/2896

While HTTPS -> HTTP redirect is totally valid, it's indeed not best practice. Would you please configure Apache to redirect directly to the final URL? Thanks.

**Comment by GyanD** [comment]
Should be fixed.

**Comment by zmwangx** [comment]
Cool, confirmed. Thanks for the quick response.
