### ISSUE TITLE
libx264rgb error

### ISSUE THREAD

**Issue by Fernando11101** [GyanD/codexffmpeg#30]
Hi, @GyanD I have a problem with the libx264rgb.

When i was using ffmpeg i use libx264rgb to convert videos.

But when I converted a video there was a error.

I will put you a picture so that you can see what happened.

Original:
![Test](https://user-images.githubusercontent.com/44506229/131782560-cea1fd3b-bb54-4ed8-a252-6dcda53f6d98.png)
Converted in libx264rgb:
![Test-1](https://user-images.githubusercontent.com/44506229/131782580-a34e253d-7611-44db-9d6e-98a444eda8b5.png)

if you could fix the libx264rgb error?

**Comment by GyanD** [comment]
Can't reproduce here.

Ask a Q at [VP.se](https://video.stackexchange.com/) showing full command + full logs, and the player in which you tested.
