### ISSUE TITLE
libx264rgb error

### ISSUE THREAD

**Issue by Fernando11101** [GyanD/codexffmpeg#31]
Hi, @GyanD I have a problem with the libx264rgb.

When i was using ffmpeg i use libx264rgb to convert videos.

But when I converted a video there was a error.

I will put you a picture so that you can see what happened.

Original:

https://user-images.githubusercontent.com/44506229/131785658-bbb64060-bf71-4877-b727-ee18537c06fd.mp4

C:\Users\ferna\Downloads\FFmpeg\FFmpeg>ffmpeg -to 00:00:05 -i "..\Gamer Webcam Meme\Very Epic Gamer Webcam.mp4" -c:v libx264 -map 0:0 "..\..\Test.mp4"
ffmpeg version 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil 57. 4.101 / 57. 4.101
libavcodec 59. 6.100 / 59. 6.100
libavformat 59. 4.102 / 59. 4.102
libavdevice 59. 0.101 / 59. 0.101
libavfilter 8. 7.100 / 8. 7.100
libswscale 6. 0.100 / 6. 0.100
libswresample 4. 0.100 / 4. 0.100
libpostproc 56. 0.100 / 56. 0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '..\Gamer Webcam Meme\Very Epic Gamer Webcam.mp4':
Metadata:
major_brand : mp42
minor_version : 0
compatible_brands: mp42mp41
creation_time : 2020-10-04T02:38:22.000000Z
Duration: 00:04:01.53, start: 0.000000, bitrate: 5321 kb/s
Stream #0:00x1: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1728x1080, 5000 kb/s, 15 fps, 15 tbr, 30k tbn (default)
Metadata:
creation_time : 2020-10-04T02:38:23.000000Z
handler_name : ?Mainconcept Video Media Handler
vendor_id : [0][0][0][0]
encoder : AVC Coding
Stream #0:10x2: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
Metadata:
creation_time : 2020-10-04T02:38:23.000000Z
handler_name : #Mainconcept MP4 Sound Media Handler
vendor_id : [0][0][0][0]
Stream mapping:
Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 000001b5f3920440] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX XOP FMA3 BMI2 AVX2
[libx264 @ 000001b5f3920440] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 000001b5f3920440] 264 - core 164 r3065 ae03d92 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=15 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '..\..\Test.mp4':
Metadata:
major_brand : mp42
minor_version : 0
compatible_brands: mp42mp41
encoder : Lavf59.4.102
Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1728x1080, q=2-31, 15 fps, 15360 tbn (default)
Metadata:
creation_time : 2020-10-04T02:38:23.000000Z
handler_name : ?Mainconcept Video Media Handler
vendor_id : [0][0][0][0]
encoder : Lavc59.6.100 libx264
Side data:
cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame= 75 fps=4.6 q=-1.0 Lsize= 1531kB time=00:00:04.80 bitrate=2612.3kbits/s speed=0.297x
video:1529kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.116314%
[libx264 @ 000001b5f3920440] frame I:1 Avg QP:21.75 size: 77841
[libx264 @ 000001b5f3920440] frame P:19 Avg QP:19.90 size: 36004
[libx264 @ 000001b5f3920440] frame B:55 Avg QP:21.47 size: 14600
[libx264 @ 000001b5f3920440] consecutive B-frames: 1.3% 2.7% 0.0% 96.0%
[libx264 @ 000001b5f3920440] mb I I16..4: 46.9% 44.6% 8.5%
[libx264 @ 000001b5f3920440] mb P I16..4: 19.3% 19.1% 1.9% P16..4: 37.6% 10.5% 4.5% 0.0% 0.0% skip: 7.1%
[libx264 @ 000001b5f3920440] mb B I16..4: 3.0% 2.5% 0.2% B16..8: 39.8% 5.3% 0.7% direct: 6.3% skip:42.2% L0:47.7% L1:48.0% BI: 4.3%
[libx264 @ 000001b5f3920440] 8x8 transform intra:46.2% inter:82.0%
[libx264 @ 000001b5f3920440] coded y,uvDC,uvAC intra: 33.9% 48.0% 6.2% inter: 16.8% 27.0% 0.0%
[libx264 @ 000001b5f3920440] i16 v,h,dc,p: 29% 25% 23% 22%
[libx264 @ 000001b5f3920440] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 22% 19% 34% 3% 5% 6% 5% 3% 3%
[libx264 @ 000001b5f3920440] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 15% 19% 3% 12% 13% 7% 4% 3%
[libx264 @ 000001b5f3920440] i8c dc,h,v,p: 53% 20% 22% 4%
[libx264 @ 000001b5f3920440] Weighted P-Frames: Y:21.1% UV:10.5%
[libx264 @ 000001b5f3920440] ref P L0: 55.8% 9.8% 21.2% 11.2% 1.9%
[libx264 @ 000001b5f3920440] ref B L0: 84.8% 11.9% 3.3%
[libx264 @ 000001b5f3920440] ref B L1: 92.8% 7.2%
[libx264 @ 000001b5f3920440] kb/s:2503.84

C:\Users\ferna\Downloads\FFmpeg\FFmpeg>ffmpeg -i "..\..\Test.mp4"
ffmpeg version 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil 57. 4.101 / 57. 4.101
libavcodec 59. 6.100 / 59. 6.100
libavformat 59. 4.102 / 59. 4.102
libavdevice 59. 0.101 / 59. 0.101
libavfilter 8. 7.100 / 8. 7.100
libswscale 6. 0.100 / 6. 0.100
libswresample 4. 0.100 / 4. 0.100
libpostproc 56. 0.100 / 56. 0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '..\..\Test.mp4':
Metadata:
major_brand : isom
minor_version : 512
compatible_brands: isomiso2avc1mp41
encoder : Lavf59.4.102
Duration: 00:00:05.00, start: 0.000000, bitrate: 2507 kb/s
Stream #0:00x1: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1728x1080, 2504 kb/s, 15 fps, 15 tbr, 15360 tbn (default)
Metadata:
handler_name : ?Mainconcept Video Media Handler
vendor_id : [0][0][0][0]
At least one output file must be specified

Converted in libx264rgb:

https://user-images.githubusercontent.com/44506229/131785792-e85bf3c5-3386-468e-b09c-c7869d4e1db0.mp4

C:\Users\ferna\Downloads\FFmpeg\FFmpeg>ffmpeg -to 00:00:05 -i "..\Gamer Webcam Meme\Very Epic Gamer Webcam.mp4" -c:v libx264rgb -map 0:0 "..\..\Test (1).mp4"
ffmpeg version 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil 57. 4.101 / 57. 4.101
libavcodec 59. 6.100 / 59. 6.100
libavformat 59. 4.102 / 59. 4.102
libavdevice 59. 0.101 / 59. 0.101
libavfilter 8. 7.100 / 8. 7.100
libswscale 6. 0.100 / 6. 0.100
libswresample 4. 0.100 / 4. 0.100
libpostproc 56. 0.100 / 56. 0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '..\Gamer Webcam Meme\Very Epic Gamer Webcam.mp4':
Metadata:
major_brand : mp42
minor_version : 0
compatible_brands: mp42mp41
creation_time : 2020-10-04T02:38:22.000000Z
Duration: 00:04:01.53, start: 0.000000, bitrate: 5321 kb/s
Stream #0:00x1: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1728x1080, 5000 kb/s, 15 fps, 15 tbr, 30k tbn (default)
Metadata:
creation_time : 2020-10-04T02:38:23.000000Z
handler_name : ?Mainconcept Video Media Handler
vendor_id : [0][0][0][0]
encoder : AVC Coding
Stream #0:10x2: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
Metadata:
creation_time : 2020-10-04T02:38:23.000000Z
handler_name : #Mainconcept MP4 Sound Media Handler
vendor_id : [0][0][0][0]
Stream mapping:
Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264rgb))
Press [q] to stop, [?] for help
[libx264rgb @ 0000018962910440] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX XOP FMA3 BMI2 AVX2
[libx264rgb @ 0000018962910440] profile High 4:4:4 Predictive, level 4.0, 4:4:4, 8-bit
[libx264rgb @ 0000018962910440] 264 - core 164 r3065 ae03d92 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=15 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '..\..\Test (1).mp4':
Metadata:
major_brand : mp42
minor_version : 0
compatible_brands: mp42mp41
encoder : Lavf59.4.102
Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), rgb24(pc, bt709, progressive), 1728x1080, q=2-31, 15 fps, 15360 tbn (default)
Metadata:
creation_time : 2020-10-04T02:38:23.000000Z
handler_name : ?Mainconcept Video Media Handler
vendor_id : [0][0][0][0]
encoder : Lavc59.6.100 libx264rgb
Side data:
cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame= 75 fps=3.2 q=-1.0 Lsize= 3896kB time=00:00:04.80 bitrate=6649.5kbits/s speed=0.203x x
video:3894kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.046165%
[libx264rgb @ 0000018962910440] frame I:1 Avg QP:24.03 size:221164
[libx264rgb @ 0000018962910440] frame P:19 Avg QP:22.22 size: 90422
[libx264rgb @ 0000018962910440] frame B:55 Avg QP:23.56 size: 37237
[libx264rgb @ 0000018962910440] consecutive B-frames: 1.3% 2.7% 0.0% 96.0%
[libx264rgb @ 0000018962910440] mb I I16..4: 19.6% 69.6% 10.8%
[libx264rgb @ 0000018962910440] mb P I16..4: 20.3% 23.2% 2.4% P16..4: 25.4% 16.5% 10.1% 0.0% 0.0% skip: 2.2%
[libx264rgb @ 0000018962910440] mb B I16..4: 3.9% 3.7% 0.5% B16..8: 41.3% 5.5% 1.2% direct:13.6% skip:30.4% L0:44.7% L1:42.3% BI:13.0%
[libx264rgb @ 0000018962910440] 8x8 transform intra:50.4% inter:74.2%
[libx264rgb @ 0000018962910440] coded y,u,v intra: 28.9% 44.8% 42.0% inter: 16.8% 37.6% 33.9%
[libx264rgb @ 0000018962910440] i16 v,h,dc,p: 28% 26% 26% 20%
[libx264rgb @ 0000018962910440] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 23% 35% 3% 3% 4% 4% 3% 3%
[libx264rgb @ 0000018962910440] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 17% 22% 3% 9% 10% 6% 4% 3%
[libx264rgb @ 0000018962910440] Weighted P-Frames: Y:21.1% UV:15.8%
[libx264rgb @ 0000018962910440] ref P L0: 49.9% 8.7% 23.3% 14.9% 3.2%
[libx264rgb @ 0000018962910440] ref B L0: 84.9% 12.0% 3.1%
[libx264rgb @ 0000018962910440] ref B L1: 93.3% 6.7%
[libx264rgb @ 0000018962910440] kb/s:6379.53

C:\Users\ferna\Downloads\FFmpeg\FFmpeg>ffmpeg -i "..\..\Test (1).mp4"
ffmpeg version 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil 57. 4.101 / 57. 4.101
libavcodec 59. 6.100 / 59. 6.100
libavformat 59. 4.102 / 59. 4.102
libavdevice 59. 0.101 / 59. 0.101
libavfilter 8. 7.100 / 8. 7.100
libswscale 6. 0.100 / 6. 0.100
libswresample 4. 0.100 / 4. 0.100
libpostproc 56. 0.100 / 56. 0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '..\..\Test (1).mp4':
Metadata:
major_brand : isom
minor_version : 512
compatible_brands: isomiso2avc1mp41
encoder : Lavf59.4.102
Duration: 00:00:05.00, start: 0.000000, bitrate: 6383 kb/s
Stream #0:00x1: Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuvj444p(pc, bt709), 1728x1080, 6380 kb/s, 15 fps, 15 tbr, 15360 tbn (default)
Metadata:
handler_name : ?Mainconcept Video Media Handler
vendor_id : [0][0][0][0]
At least one output file must be specified

if you could fix the libx264rgb error?

**Comment by GyanD** [comment]
I've identified the issue and it is a bug in ffmpeg, not the build, so I'll resolve it at VP. Post these details there.
