### ISSUE TITLE
Invalid DTS error

### ISSUE THREAD

**Issue by pepeu93** [GyanD/codexffmpeg#32]
I'm currently using this code to capture 3 windows at once, scale them to the same dimension, and save their output side by side.
The problem is,  it keeps throwing a message in the console the entire time about **Invalid DTS**, the output file is being saved correctly, but as it spams this message so fast, it's causing the console to `increase `the use of  CPU.

`ffmpeg -f gdigrab -framerate 30 -i title="" -f gdigrab -framerate 30 -i title="" -f gdigrab -framerate 30 -i title="" -vsync 2 -c:v h264_nvenc -filter_complex "[0]scale=830:500:force_original_aspect_ratio=decrease,setsar=1[left];[1]scale=830:500:force_original_aspect_ratio=decrease,setsar=1[left2];[2]scale=830:500:force_original_aspect_ratio=decrease,setsar=1[right];[left][left2][right]hstack=inputs=3" output.mp4`

Here is the log: pastebin.com/7w4x8HXc
Any idea what's going on?

**Comment by pepeu93** [comment]
Pastebin linked has expired, uploading it again;
https://pastebin.com/8WmnN3k1

**Comment by GyanD** [comment]
Don't worry about it. The GDI capture does not provide decoding timestamps so ffmpeg assigns one.
