### ISSUE TITLE
Question about encoder libkvazaar

### ISSUE THREAD

**Issue by GrilledPear** [GyanD/codexffmpeg#35]
Question: why libkvazaar is not included in the full build. 

From what I've seen in https://github.com/m-ab-s/media-autobuild_suite (see screenshot below). This library seems to fail on lots of its builds. Is this the main reason?

![image](https://user-images.githubusercontent.com/90295422/135717061-9a111e0a-37e4-4e0d-9d5e-295fabb9ebb4.png)

**Comment by GyanD** [comment]
Kvazaar describes itself as an "academic open-source video encoder" with goals "Coding efficiency close to HM" and "Real- time coding speed" - both very low bars. And I've rarely come across anyone using it.

There's no value proposition for it. x265 is much slower than x264 (but faster than realtime) whereas GPU HEVC encoders are much faster.
