### ISSUE TITLE
Enable AVS2/3 encoder, please.

### ISSUE THREAD

**Issue by lenny20** [GyanD/codexffmpeg#36]
AVS2/3 (IEEE 1857, GPL v2) is faster and easier than H265 or AV1, and the patent licensing fees is very simple and affordable.
BtbN is taked my advice. Your website is faster usually. Encoder is enough in most case.
Thank you, very much!

**Comment by GyanD** [comment]
Added libdavs2, libxavs2 and libuavs3d to full builds.
