### ISSUE TITLE
Release dates

### ISSUE THREAD

**Issue by rgiuffre** [GyanD/codexffmpeg#37]
I'm assuming that you're building the releases after midnight from the previous day. So the current says "11-04-2021", but actually the file version says "11-03-2021".  Can you match the release date with the actual file version number, please?

Thank you for hosting!

**Comment by GyanD** [comment]
The last and next build dates refer to the date on which the build is generated. The date in the package version is the date of the latest commit at the time if build. Sometimes that may be a day or two earlier.
