### ISSUE TITLE
Firefox virus warning when downloading ffmpeg-tools.zip

### ISSUE THREAD

**Issue by deroverda** [GyanD/codexffmpeg#38]
This is really odd. This must be the first time I ever see a virus warning in Firefox. See image below.
![Du1bFteL3k - Copy](https://user-images.githubusercontent.com/70813982/143076073-5319e108-599b-4adb-b7db-5487f744d428.png)

**Comment by GyanD** [comment]
See #11 

False positives. Get it from the github mirror.

https://www.virustotal.com/gui/url/f8934db2c1deb8818b35eccde749e4ffae165d085cd686961f805627e77a5a27

**Comment by deroverda** [comment]
@GyanD 

ofc I should have searched before posting an issue, sry about that. I''ll close this. 

PS. Loving your builds, stable and without any issues. Have a good day.
