### ISSUE TITLE
Any way to tell if the x265 included is 10 or 12 bit capable

### ISSUE THREAD

**Issue by mshiels** [GyanD/codexffmpeg#43]
The normal way i check is running x265... but when it's all built into ffmpeg, hard to tell what capabilities it was built with originally right? or am I missing something?

**Comment by GyanD** [comment]
The build has support for all three - 8, 10 & 12 bit.

Run `ffmpeg -h encoder=libx265 `

and check `Supported pixel formats:`

`Supported pixel formats: yuv420p yuvj420p yuv422p yuvj422p yuv444p yuvj444p gbrp yuv420p10le yuv422p10le yuv444p10le gbrp10le yuv420p12le yuv422p12le yuv444p12le gbrp12le gray gray10le gray12le`
