### ISSUE TITLE
Please create a simple GUI for it

### ISSUE THREAD

**Issue by BestNoob** [GyanD/codexffmpeg#45]
I recognized that there often some things removed, edited or changed so older GUI and Programs doesnt work correctly with new ffmpeg versions. In the end all programs also the ones u have to pay for use ffmpeg.

It would be great when you guys create a simple GUI for it that dynamicly list up all aviable commands/paremeters depending to codec and the other options. 

I tried it myself the past 2 days via CMD but i had a lot issues to find good settings.

**Comment by GyanD** [comment]
That's not a completely tractable problem, and would require a decent dose of heuristics. Which will leave many unsatisfied users.
