### ISSUE TITLE
Question: What's the recommended algorithm for comparing versions, checking for updates?

### ISSUE THREAD

**Issue by LuminairPrime** [GyanD/codexffmpeg#47]
I couldn't find a simple ffmpeg updater for Windows, so I decided to learn Python and write one for myself. Can you lay down the law for me so I know how to check if there's an update? I'll tell you my guess first: I don't think ffmpeg has an official standardized version output as nice as your web one, but I think I could check if the first line of ffmpeg -version contains your version at https://www.gyan.dev/ffmpeg/builds/release-version and if it's not there, blast the old file with an update. That's imprecise, but it would seem to work, and the cost of getting it wrong wouldn't be large.

I'd love to know what version comparison and update algorithm you'd recommend! 

Thank you Gyan for your work keeping the Windows world on ffmpeg.

**Comment by GyanD** [comment]
Download and save the version files (git-version, release-version) for reference. To check for updates, download the current files and compare against reference. A simple text diff will do. If changed, there's been a new release. Update reference and repeat.

**Comment by LuminairPrime** [comment]
I was thinking about all the trades here, whether I do data storage or support overwriting with other builds manually. And then I had a slightly wild idea that I can put in a separate issue if you like it lol:

What if we had a doppleganger ffmpeg.exe that downloaded your build, renamed it to ffmpeg[ver].exe, and forward the command line args to it. The filename itself stores the version data for fast update checks. Operate on the last alphabetically-sorted ffmpeg*.exe in the file system; not rigorous, but it should work. No change to the ffmpeg project or building it. Any downstream Windows project that uses ffmpeg (and is plagued with out-of-date versions like I am) could include that "shim" ffmpeg.exe and always be up-to-date without doing any work themselves. We could call it "Gyan ffmpeg Autoupdater"! ;)
