### ISSUE TITLE
DCONFIG_TUNE_VMAF=1

### ISSUE THREAD

**Issue by 9W5iw** [GyanD/codexffmpeg#48]
Hello I have problems using vmaf tune. Maybe Im doing something wrong but with:

ffmpeg  -i input.mkv -c:v libaom-av1 -some_options  -aom-params some_params:tune=vmaf  -c:a copy output.mkv

I get this error:

[libaom-av1 @ 000001c2d1247940] 3.3.0-408-g4becfef8d
[libaom-av1 @ 000001c2d1247940] tune: Invalid parameter
[libaom-av1 @ 000001c2d1247940]   Additional information: This error may be related to the wrong configuration options: try to set -DCONFIG_TUNE_VMAF=1 at the time CMake is run.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

Without vmaf tune it works perfectly

**Comment by GyanD** [comment]
Apparently, only available with the standalone app aomenc, not libaom. Reopen if you have verified that libaom supports it.
