### ISSUE TITLE
ffmeg full build doesnt extract to C:\Program Files\ffmpeg

### ISSUE THREAD

**Issue by knsmastin** [GyanD/codexffmpeg#49]
Windows 10. I downloaded the full ffmpeg build, and installed the 7z extractor. Errors are cannot create file C:\Program Files\ffmpeg\ffmpeg <and all the files that are supposed to extract to this folder>
This is my daughters computer. Im not a windows guy, I use linux for  more than 20 years.
Any help is appreciated.
TIA

**Comment by GyanD** [comment]
You may not have sufficient permission to extract inside `C:\Program Files`. Try another parent folder.
