### ISSUE TITLE
Cannot use inbuilt vmaf model?

### ISSUE THREAD

**Issue by ls-milkyway** [GyanD/codexffmpeg#51]
Command to use in built models in vmaf is not working in your build?

**Command:** `ffmpeg.exe  -f lavfi -i color=c=black:s=640x480:d=1 -filter_complex "[0:v][0:v]libvmaf=model=version=vmaf_v0.6.1" -f null -`

**BtbN Output:**
![btbn](https://user-images.githubusercontent.com/55090624/166314077-1cd9d6ed-e2cc-4ecb-a4fc-bb5e1c3b45bc.png)

**Gyan Output:**
![gyan](https://user-images.githubusercontent.com/55090624/166314174-096e5d7d-f010-4402-828f-86770fc0af8c.png)

**Probabale Cause:** Unix-Windows path interoperability .....as BtbN is cross-compiled.

Plz suggest ...I have tried lot of combinations ......fmpeg docs are outdated......even built my own FFmpeg with gcc & MSYS2 project...but the result is same.

**Comment by GyanD** [comment]
You're comparing BtbN's git release of 2022-05-02 with my 5.0.1 release build. The ability to use inbuilt models in VMAF was added to ffmpeg after the 5.0 release branch was cut. Use my current git builds for that feature.
