### ISSUE TITLE
Option decryption_key not found

### ISSUE THREAD

**Issue by 89z** [GyanD/codexffmpeg#53]
Running this command:

~~~
ffmpeg -decryption_key 13d7c7cf295444944b627ef0ad2c1b3c
-i https://...242741a6ab8d0dfefbd662ca/87fe48887c78431d823a845b377a0c0f/index.mpd
-map 0:8 -c copy outfile.mp4
~~~

I get this result:

~~~
Option decryption_key not found.
~~~

**Comment by GyanD** [comment]
That's a DASH input, which does not directly support that option.

Try adding `crypto+` before the input URL i.e.  `crypto+https://..`

**Comment by 89z** [comment]
I get this result:

~~~
[crypto @ 000002593833bec0] decryption IV not set
crypto+https://...ca/87fe48887c78431d823a845b377a0c0f/index.mpd: Invalid argument
~~~

**Comment by GyanD** [comment]
Your "key" is likely KEY+IV, so set first 16 characters as key and last 16 as IV and check. Try the reverse as well.

**Comment by 89z** [comment]
~~~
[crypto @ 000002a6f34cc800] invalid decryption key size (8 bytes, block size is 16)
crypto+https://...1a6ab8d0dfefbd662ca/87fe48887c78431d823a845b377a0c0f/index.mpd:
Invalid argument
~~~

**Comment by GyanD** [comment]
Last try:  use full key and set 32 zeros for IV.

**Comment by 89z** [comment]
I get the previous error:

~~~
crypto+https://...1a6ab8d0dfefbd662ca/87fe48887c78431d823a845b377a0c0f/index.mpd:
Invalid data found when processing input
~~~

Note that I also asked BtbN, and they said this:

> The decryption_key option only exists on the mp4/mov demuxer, and nowhere else from what I can tell: https://ffmpeg.org/ffmpeg-all.html#mov_002fmp4_002f3gp
> 
> The HLS demuxer can forward to that option, but other than that, I see no obvious way to set it for DASH demuxing. You could download the segments manually, and then the mp4 demuxer will recognize the option.

I was hoping they were wrong.

**Comment by GyanD** [comment]
Then the issue is likely that the encryption is not applied to the full stream I/O but at the container level. Decrypting that for a DASH parent format is not currently supported. If you can supply a valid full DASH URL + key + iv, I can test adding that support over the weekend.

**Comment by GyanD** [comment]
Ok. Email is on my site.

**Comment by GyanD** [comment]
Added option cenc_decryption_key to DASH demuxer.

`ffmpeg -cenc_decryption_key 13d7c7cf295444944b627ef0ad2c1b3c -i https://... `

**Comment by 89z** [comment]
great work, thank you! Did you do it upstream too, or is it just for the builds here?

**Comment by GyanD** [comment]
It's in upstream now. My Monday build will have it.

**Comment by 89z** [comment]
wow that's amazing! You are a good guy

**Comment by 89z** [comment]
Good morning - is it possible to decrypt an entire file? Currently it seems I need to do:

~~~
init.m4f + segment0.m4f
init.m4f + segment1.m4f
...
~~~

I would like to do:

~~~
init.m4f + segment0.m4f + segment1.m4f + ...
~~~
