### ISSUE TITLE
cenc

### ISSUE THREAD

**Issue by Yaya7** [GyanD/codexffmpeg#55]
hey gyan thanks for adding cenc decryption key option 
the some url require 2 key to download or to be working video  and audio 
if possible to add a function to add more keys if possible thanks

**Comment by GyanD** [comment]
Share input URL.

**Comment by 89z** [comment]
I don't think the original comment is correct. From my experience, certain tools do output multiple keys, but usually only one key is actually required.

**Comment by Yaya7** [comment]
@89z u are wrong many input now need multiple keys @GyanD i sent you email with input url and keys thanks

**Comment by Yaya7** [comment]
https://ssc-7-ak.akamaized.net/out/v1/25e894f0722046648dba96a8c62509b1/index.mpd

**Comment by 89z** [comment]
That MPD uses Widevine [1]:

~~~
<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
</ContentProtection>
~~~

So its useless without a key, or without the license server information.

1. <https://dashif.org/identifiers/content_protection>

**Comment by Yaya7** [comment]
I have keys

**Comment by Yaya7** [comment]
Have 3 keys that why i told gyan if its possibly to add 3keys or 4key in 1 input as now supported 1key only

**Comment by 89z** [comment]
Unless you can provide the keys, or the license server information, then you haven't demonstrated that more than one key is actually needed. Until that can be done, I don't think this feature should be implemented.

**Comment by Yaya7** [comment]
lol i told u already i have them 

MPD: https://dsh-m011-live-aka-canalplus.akamaized.net/live/disk/canalplus-hd/dash-fhddvr/canalplus-hd.mpd
video key  1e29fd20c2bf49189ac45deb7f893d8e:0108a366810bce514d59ac5516212985
audio key  7fd57b8773a942e3a78f697e83ae62eb:666bc223a9bebb551c69930c9feee90d

and this i geolocked

when im saying something that is tested already and only video can be decoded by gyan feature need another  cenc decryption for audio

**Comment by 89z** [comment]
You can get those already like this:

~~~
ffmpeg -cenc_decryption_key 0108a366810bce514d59ac5516212985 -i https://... -map [video stream]
ffmpeg -cenc_decryption_key 666bc223a9bebb551c69930c9feee90d -i https://... -map [audio stream]
~~~

I guess it could be useful to have a single command for both, but its not required

**Comment by Yaya7** [comment]
yeah i need to put in a single command thanks for you help @89z waiting gyan reply

**Comment by GyanD** [comment]
Can't access the URL in the email. 406 error.

**Comment by Yaya7** [comment]
https://hls-m011.live-lv3.canalplus-cdn.net/live/disk/canalplus-hd/dash-fhddvr/canalplus-hd.mpd

video 0108a366810bce514d59ac5516212985

audio 666bc223a9bebb551c69930c9feee90d

This ?

**Comment by GyanD** [comment]
Yes.

**Comment by Yaya7** [comment]
Working for me can you try vpn france pls

**Comment by GyanD** [comment]
Ni, I can't. Need a directly accessible test case.

**Comment by GyanD** [comment]
Only directly accessible URLs.

**Comment by Yaya7** [comment]
Some url have 1 key some 4 key
