### ISSUE TITLE
zscale error with some files in newer versions [since last month or so] [Windows 10 "reduced"]

### ISSUE THREAD

**Issue by bokeron2020** [GyanD/codexffmpeg#57]
I'm having a problem with a given set of files -- but everything works OK with every other file I've tried so far. I've been testing a few things and in the end it seems that something in my customized Windows 10 x64 install, something I deleted or deactivated, is causing this problem.

I'm asking here trying to find out what might be so I can find a solution. If this is not the place then, please, forgive me and delete the post.
Meanwhile, I'll expose the situation.

- All previous versions until a month or so worked perfectly.
- Latest version DO work with most files EXCEPT a bunch of mp4/mkv h-264 encoded videos.
- Even with those files, everything works until I use zscale to change image size... so I'd say this seem to be related to some of zimg new changes.
- When the problem appears I get an **[Parsed_zscale_0 @ ...] code 2050: active window must be positive** error.

In other words, everything was working with _ffmpeg-2022-05-04-git-0914e3a14a-essentials_build_ ... and everything still works with _ffmpeg-2022-05-16-git-e3580f6077-essentials_build_ **except for** zscale video resizing, **and only in** these videos... **and only in** my modified Windows install.

I've attached a sample file:
https://user-images.githubusercontent.com/63074669/173467762-fbcd71bc-9228-4c63-bb33-0b5d32d4dc53.mp4

I would like to know if this is supposed to happen because _something_ inside ffmpeg now relies on _something_ I've never had in my Win install, something that ffmpeg [zimg ?] didn't need in previous versions.

I hope something of what I've wrote makes sense. It looks quite confusing and english isn't my native laguage so I've surely messed it even more.

Where could be the problem? Can be considered a "pre-bug" of a kind?
What is ffmpeg expecting that exists in Windows now that it didn't used before?

**Comment by GyanD** [comment]
Changes were made to the zscale wrapper on May 13th so could be related to that.

This is best continued at [#9811](https://trac.ffmpeg.org/ticket/9811) on the bug tracker at trac.ffmpeg.org.

**Comment by bokeron2020** [comment]
Thanks!
