### ISSUE TITLE
add service provider in programe like program_num

### ISSUE THREAD

**Issue by ansariatif** [GyanD/codexffmpeg#59]
hi gyan,
cant set provider/publisher in mpts stream its shows default "FFMPEG"

this is my command 

ffmpeg  -thread_queue_size 256  -i "udp://224.2.2.2:2000?fifo_size=1000000&buffer_size=10000000" -thread_queue_size 256 -i "udp://224.2.2.2:3008?fifo_size=1000000&buffer_size=10000000"  -map 0  -map 1  -program title="Xren0":program_num=100:st=0:st=1 -program title="Xren1":program_num=101:st=2:st=3  -c copy  -f mpegts -metadata service_provider="test"  -muxrate 40000000 -flush_packets 0 "udp://239.2.2.2:2222?overrun_nonfatal=1&fifo_size=1000000&buffer_size=10000000&pkt_size=1316&ttl=1&bitrate=40000000"

unable to set provider name . it shows ffmpeg default

![image](https://user-images.githubusercontent.com/13900715/175532199-f43ca2fb-b36c-4763-aeea-e0c760fca7d9.png)

![image](https://user-images.githubusercontent.com/13900715/175532285-1c857bcd-dd1d-4c6c-9c84-9d761f533088.png)

**Comment by GyanD** [comment]
You have to qualify the metadata specifier.   `-metadata:p:0 service_provider="test"`

**Comment by ansariatif** [comment]
Thanks it works. one more thing can we extract scte-35 marker information in udp mpegts?
