### ISSUE TITLE
When extracting Closed Captions, how do I turn off: Data Ignored since exceeding screen width

### ISSUE THREAD

**Issue by rgiuffre** [GyanD/codexffmpeg#60]
Is there a command line option to turn off it truncating subtitles or closed captions if the screen width is exceeded?
I can edit the .srt file to fix them after they've been converted.

This is the command line I am using:

FOR %%F IN (*.mp4) DO ffmpeg -f lavfi -i movie="%%F"[out+subcc] -map 0:1 -y "%%~nF.srt"

![Subtitle-Errors](https://user-images.githubusercontent.com/33906215/176965687-1cfa1975-26c2-48bf-9353-1cefcb57764c.png)

**Comment by GyanD** [comment]
This should be posted to ffmpeg-user or a forum like SuperUser/reddit
