### ISSUE TITLE
static library for windows

### ISSUE THREAD

**Issue by goodtogood** [GyanD/codexffmpeg#63]
great job. would you like to support static library for windows?
thanks!

**Comment by pzhlkj6612** [comment]
hi, does [BtbN/FFmpeg-Builds](https://github.com/BtbN/FFmpeg-Builds) meet your requirement?

**Comment by goodtogood** [comment]
@pzhlkj6612 
thanks for information.
I've found that repo. you referred to.
It releases excutable binary exe and shared library (.dll and .so).
actually there's no static library (.lib).

**Comment by GyanD** [comment]
Have you seen inside the release-shared packages?

**Comment by pzhlkj6612** [comment]
> It releases excutable binary exe and shared library (.dll and .so).
> actually there's no static library (.lib).

Well, if you could see the ".exe" and ".dll" files, you might be in the "/bin" directory of a "\*-shared" package. Did you see the "/lib" directory at the upper level?
