### ISSUE TITLE
Winget support?

### ISSUE THREAD

**Issue by DanTheMan827** [GyanD/codexffmpeg#64]
Would it be possible to have an installer made for these and it submitted to [@microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)?

The big thing for that is that the uninstall entry has a proper version key set and that it isn't included in the name of the program.

**Comment by GyanD** [comment]
When I last looked into winget, they needed a signed MSI installer, which is a hassle.

Consider using Scoop or Chocolatey, both of which will install my latest release builds.

**Comment by DanTheMan827** [comment]
@GyanD winget accepts any installer that has a silent command line switch.

Nullsoft, MSI, and other install systems are supported out of the box, and none of them have to be signed.

**Comment by sitiom** [comment]
> When I last looked into winget, they needed a signed MSI installer, which is a hassle.

Winget now supports zip installation, and a PR is underway:
- https://github.com/microsoft/winget-pkgs/pull/87327

[Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) would have to be set up in this repo to enable automatic package updates. @GyanD are you ok with adding that here?

**Comment by GyanD** [comment]
1) The pkg name should be just ffmpeg, not codexffmpeg. The latter is the name of the site.
2) Is the Releaser necessary for release builds. Those are updated 2x a year, and manual update of manifest doesn't seem cumbersome. I don't see a pkg for git builds.

**Comment by sitiom** [comment]
> Is the Releaser necessary for release builds. Those are updated 2x a year, and manual update of manifest doesn't seem cumbersome. 

If you want automatic updates, yes. Automation makes things easier 🙂

> I don't see a pkg for git builds.

Someone will add it if they are interested enough.

**Comment by GyanD** [comment]
Release builds are infrequent. Let's proceed without the Releaser for now.

**Comment by sitiom** [comment]
PR is now merged. This means this can be closed?

**Comment by GyanD** [comment]
Looks like it. Thanks for the help.
