### ISSUE TITLE
Win libs are missing from both builds

### ISSUE THREAD

**Issue by manticode** [GyanD/codexffmpeg#65]
The libs (DLLs) are missing from the 'essentials' and 'full' build. Tested 5.1 and also git master build.

The bin folder only has ffmpeg.exe, ffplay.exe and ffprobe.exe, but I expected to find the DLL files in there also.

**Comment by GyanD** [comment]
Only the release shared* build has dynamic linking. All other builds are statically linked, so one EXE only.

* https://github.com/GyanD/codexffmpeg/releases/download/5.1/ffmpeg-5.1-full_build-shared.zip
