### ISSUE TITLE
ffprobe 5.1 always shows errorlevel 0

### ISSUE THREAD

**Issue by wallobit** [GyanD/codexffmpeg#66]
In my batch, ffprobe 5.1 always returns errorlevel 0, regardless of whether the file/stream address is present. In 5.0.1 this still worked. Unfortunately, I can't judge whether this is due to ffmpeg or the Windows build of gyan.dev.

**Comment by GyanD** [comment]
Regression in code. Looking into it. Thanks.

**Comment by GyanD** [comment]
Will be fixed in the next git and release build.
