### ISSUE TITLE
Out Of Memory (malloc) error when using any codec! 

### ISSUE THREAD

**Issue by BinarySwami-10** [GyanD/codexffmpeg#67]
# LOG
> C:\Users\User\Desktop\ffmpeg-2022-08-31-git-319e8a49b5-full_build\ffmpeg-5.1.1-full_build\bin>ffmpeg -rtbufsize 128M -i input.mp4 -vcodec libx264 -crf 28   output.mp4 -y
> ffmpeg version 2021-09-30-git-3ee4502753-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
>   built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
>   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
>   libavutil      57.  7.100 / 57.  7.100
>   libavcodec     59.  9.101 / 59.  9.101
>   libavformat    59.  5.100 / 59.  5.100
>   libavdevice    59.  0.101 / 59.  0.101
>   libavfilter     8. 10.100 /  8. 10.100
>   libswscale      6.  1.100 /  6.  1.100
>   libswresample   4.  0.100 /  4.  0.100
>   libpostproc    56.  0.100 / 56.  0.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'input.mp4':
>   Metadata:
>     major_brand     : mp42
>     minor_version   : 0
>     compatible_brands: mp42mp41isomavc1
>     creation_time   : 2020-10-31T22:00:53.000000Z
>   Duration: 00:00:09.90, start: 0.000000, bitrate: 300 kb/s
>   Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m, progressive), 426x240, 296 kb/s, 30 fps, 30 tbr, 30 tbn (default)
>     Metadata:
>       creation_time   : 2020-10-31T22:00:53.000000Z
>       handler_name    : L-SMASH Video Handler
>       vendor_id       : [0][0][0][0]
>       encoder         : AVC Coding
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
> Press [q] to stop, [?] for help
> [libx264 @ 000000001a9b0c40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
> [libx264 @ 000000001a9b0c40] profile High, level 2.1, 4:2:0, 8-bit
> [libx264 @ 000000001a9b0c40] 264 - core 164 r3065 ae03d92 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
> Output #0, mp4, to 'output.mp4':
>   Metadata:
>     major_brand     : mp42
>     minor_version   : 0
>     compatible_brands: mp42mp41isomavc1
>     encoder         : Lavf59.5.100
>   Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, smpte170m, progressive), 426x240, q=2-31, 30 fps, 15360 tbn (default)
>     Metadata:
>       creation_time   : 2020-10-31T22:00:53.000000Z
>       handler_name    : L-SMASH Video Handler
>       vendor_id       : [0][0][0][0]
>       encoder         : Lavc59.9.101 libx264
>     Side data:
>       cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
> Error while decoding stream #0:0: Cannot allocate memory.03 bitrate=  11.5kbits/s speed=0.052x
> Error while decoding stream #0:0: Cannot allocate memory.56 bitrate=   0.7kbits/s speed=0.373x
> [h264 @ 000000001b5c3c40] get_buffer() failed
> [h264 @ 000000001b5c3c40] thread_get_buffer() failed
> [h264 @ 000000001b5c3c40] decode_slice_header error
> [h264 @ 000000001b5c3c40] no frame!
> Error while decoding stream #0:0: Cannot allocate memory
>     Last message repeated 2 times
> [h264 @ 000000001c6b4c40] get_buffer() failed
> [h264 @ 000000001c6b4c40] thread_get_buffer() failed
> [h264 @ 000000001c6b4c40] decode_slice_header error
> [h264 @ 000000001c6b4c40] no frame!
> [h264 @ 000000001c82cc40] decode_slice_header error
> [h264 @ 000000001c82cc40] no frame!
> Error while decoding stream #0:0: Cannot allocate memory
>     Last message repeated 2 times
> input.mp4: Cannot allocate memory
> Video encoding failed
> [libx264 @ 000000001a9b0c40] frame I:1     Avg QP:26.35  size:  7759
> [libx264 @ 000000001a9b0c40] frame P:12    Avg QP:27.41  size:   483
> [libx264 @ 000000001a9b0c40] frame B:11    Avg QP:28.59  size:    51
> [libx264 @ 000000001a9b0c40] consecutive B-frames:  4.0% 96.0%  0.0%  0.0%
> [libx264 @ 000000001a9b0c40] mb I  I16..4: 21.0% 49.4% 29.6%
> [libx264 @ 000000001a9b0c40] mb P  I16..4:  0.1%  0.0%  0.0%  P16..4: 18.9%  5.2%  3.9%  0.0%  0.0%    skip:71.9%
> [libx264 @ 000000001a9b0c40] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  9.8%  0.1%  0.0%  direct: 0.0%  skip:90.1%  L0: 8.4% L1:90.8% BI: 0.8%
> [libx264 @ 000000001a9b0c40] 8x8 transform intra:48.8% inter:58.3%
> [libx264 @ 000000001a9b0c40] coded y,uvDC,uvAC intra: 58.6% 82.3% 54.6% inter: 2.2% 4.6% 0.7%
> [libx264 @ 000000001a9b0c40] i16 v,h,dc,p:  8% 10% 11% 71%
> [libx264 @ 000000001a9b0c40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 13% 16%  5%  7% 10%  6%  8%  6%
> [libx264 @ 000000001a9b0c40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 26% 18% 12%  7%  9%  9%  8%  7%  5%
> [libx264 @ 000000001a9b0c40] i8c dc,h,v,p: 47% 16% 25% 12%
> [libx264 @ 000000001a9b0c40] Weighted P-Frames: Y:0.0% UV:0.0%
> [libx264 @ 000000001a9b0c40] ref P L0: 81.9%  9.4%  6.9%  1.8%
> [libx264 @ 000000001a9b0c40] ref B L0: 90.1%  9.9%
> [libx264 @ 000000001a9b0c40] kb/s:141.10
> [h264 @ 000000001a8bdc40] Final thread update failed
> Assertion src->f->buf[0] failed at D:/code/ffmpeg/src/libavcodec/h264_picture.c:105
> 

# Issue
Please suggest why im getting out of memory/malloc issues? 
i suspect 2 things, i have 30GB VRAM SSD, Bios setting of internal graphics allocated to 256MB(also tried max value but no use)

## MY System Config
16GB RAM 2666MHZ
i7-8700 @3.4GHZ

## observation and attempts
when i try using this software https://ffmpeg-batch.sourceforge.io/ it worked fine, and when video codec set to "copy" no issues encountered. only problem with h264 library IMO. i tried changing buffer size [32M,64M,128M,1024M] threadcount like 1, 6, 12, 24, 100 etc  nothing worked, my gpu shows a small spike of usage and the above error appears every time. i doubt windows update and installed any patches, yet no progress. PLS HELP!

**Comment by GyanD** [comment]
Check with a current build. You used `ffmpeg version 2021-09-30-git-3ee4502753-full_build-www.gyan.dev`

**Comment by BinarySwami-10** [comment]
> Check with a current build. You used `ffmpeg version 2021-09-30-git-3ee4502753-full_build-www.gyan.dev`

actually it turned out , ther's no problem with build version, i tried with last 3 major versions on different pc its fine. i strongly believe on my faulty computer its some virtualization related issue with WSL and docker. and also some fishy bios setting. i did windows reset in UEFI Boot menu it working good now. thanks for help however. @microsoft must address this issue.
