### ISSUE TITLE
ffmpeg video freezes some seconds the output video

### ISSUE THREAD

**Issue by alcarazolabs** [GyanD/codexffmpeg#69]
I'm using the program ffmpeg on windows, I just downloaded the binaries from here:
https://github.com/GyanD/codexffmpeg/releases/tag/2022-09-05-git-2ed5925e26
ffmpeg-2022-09-05-git-2ed5925e26-essentials_build.zip

setted the path variable of windows to be able of use it.

I'm ran ffmpeg with python and also just running the command in the cmd

videos.txt
```
file video1.mp4
file video2.mp4
file video3.mp4
file video4.mp4
```
python script:
```
import subprocess
import shlex

subprocess.run(shlex.split('ffmpeg -f concat -safe 0  -i videos.txt -c:v libx264 -c copy output.mp4'))
```

cmd
```
ffmpeg -f concat -safe 0  -i videos.txt -c:v libx264 -c copy output.mp4
```
The output video plays fine the half of the video, but at minute 1:09 it freezes and some seconds at the end there is not sound.
I will encorage you that you test my videos downloading from here: https://github.com/alcarazolabs/ffmpeg-issue also on there is my script and the command.

I ran ffmpeg with -c:v libx264 and without it and the problem remains. Also I needed of -safe 0 but with this or not the same problem happens.

I don't know what to do now, please I need your support, I need to fix this problem as soon as possible. thanks so much

**Comment by GyanD** [comment]
Usage issues should be posted at forums like Super User or r/ffmpeg
