### ISSUE TITLE
Burn-in ASSA file sometimes changes color

### ISSUE THREAD

**Issue by niksedk** [GyanD/codexffmpeg#72]
Hi GyanD & Co.

Sometimes burn-in of Advanced Sub Station Alpha files seems to change color somewhat.

This image contains both a sample for the burned-in mp4 file and a sample from the mp4/ass playing in VLC.
As you can see the top image box is not matching the red color very well:
![image](https://user-images.githubusercontent.com/1261331/194773177-46cc2edf-7e22-415e-87bf-d7e03c848a2e.png)

[ass-and-mp4.zip](https://github.com/GyanD/codexffmpeg/files/9742314/ass-and-mp4.zip)

Using something like:
````
ffmpeg -i 2.mp4 -vf "ass=2.ass",yadif,format=yuv420p -g 30 -bf 2 -s 1920x1080 -c:v libx264 -preset medium  -crf 23 -c:a copy output.mp4
````

Any idea what causes the color to change - and if it can be fixed in some way?
(I'm using ffmpeg version 5.1.2 essentials)

**Comment by GyanD** [comment]
Usage questions belong on a forum like SuperUser or reddit r/ffmpeg.

Basically, this looks related to incomplete or wrong color props set in the input file viz. colorspace and/or range.
