### ISSUE TITLE
Suggestion : compile with libvpl 

### ISSUE THREAD

**Issue by AlyxSharkBite** [GyanD/codexffmpeg#73]
Suggestion for this. 

For reference 
https://www.intel.com/content/www/us/en/developer/articles/technical/onevpl-in-ffmpeg-for-great-streaming-on-intel-gpus.html#gs.f9vcfg

Substitute ‘--enable-libvpl’ instead of ‘--enable-libmfx' and it will enable the use of the newer API, which is still backwards compatible for older platforms but will take better advantage of the newer Intel GPUs.

**Comment by GyanD** [comment]
Will do.
