### ISSUE TITLE
skipping 1 segments ahead, expired from playlists

### ISSUE THREAD

**Issue by ansariatif** [GyanD/codexffmpeg#74]
hi Gyan,

I am  save youtube live streams with an .m3u8 url. Regularly I see the following message. This results in the output video freezing.

**skipping 2 segments ahead, expired from playlists**

i getm3u8 url using youtube-dl. 

Please help out from this.

**Comment by GyanD** [comment]
Usage questions belong on a forum like SuperUser or reddit r/ffmpeg.

This looks like your network is slow so that by the time you have downloaded some segments and refreshed the playlist, some intermediate future segments have already expired. Consider using yt-dl internal HLS downloader.
