### ISSUE TITLE
Is it possible to provide RSS?

### ISSUE THREAD

**Issue by wordlesswind** [GyanD/codexffmpeg#75]
Hello Gyan,

I want a new build alert, but haven't found a good way to do it.

Best regards,
wordlesswind

**Comment by GyanD** [comment]
Load https://www.gyan.dev/ffmpeg/builds/last-build-update and https://www.gyan.dev/ffmpeg/builds/next-build-update

**Comment by wordlesswind** [comment]
> Load https://www.gyan.dev/ffmpeg/builds/last-build-update and https://www.gyan.dev/ffmpeg/builds/next-build-update

Oh sorry, I didn't notice them.
