### ISSUE TITLE
stable URLs for older ffmpeg versions?

### ISSUE THREAD

**Issue by derhuerst** [GyanD/codexffmpeg#77]
First of all: Thanks a lot for your work running this project!

The [ffmpeg-static npm package](https://npmjs.com/package/ffmpeg-static), which I have become the maintainer of a while ago, downloads and re-distributes the binaries from your site, among several others. The idea is to ship binaries of *one specific version* of ffmpeg across all platforms, at the same time. Currently, it is very cumbersome to find moment when all those binary providers provide builds for the *same* ffmpeg version.

Therefore, we would benefit a lot from **stable URLs for specific ffmpeg releases**! You seem to do this already to some extent (there is `https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-5.0.1-essentials_build.7z` for example), but not for all releases (e.g. `https://www.gyan.dev/ffmpeg/builds/ffmpeg-5.1.1-essentials_build.7z` yields `404`). In fact, I think anyone trying to build as-reproducible-as-possible distributions channels for ffmpeg binaries would benefit a lot from this.

What do you think?

**Comment by derhuerst** [comment]
(Right now, this is relevant in https://github.com/eugeneware/ffmpeg-static/issues/110, where other binary providers only provide `5.1.1`, where as `gyan.dev/ffmpeg` only provides `5.0.1` & `5.1.2`.)

**Comment by GyanD** [comment]
So, I provide updated releases for the latest release branch only. The builds for any previous release branch remain frozen,
e.g. if 5.1.3 were released now, I would provide it. However, if 5.2 was to be released first, followed by 5.1.3 then 5.1.2 would remain the latest release from 5.1 branch.

Having said that, all releases are archived here at Github. Browse them via the Tags button.
5.1.1 is at https://github.com/GyanD/codexffmpeg/releases/tag/5.1.1

**Comment by derhuerst** [comment]
> So, I provide updated releases for the latest release branch only. The builds for any previous release branch remain frozen, e.g. if 5.1.3 were released now, I would provide it. However, if 5.2 was to be released first, followed by 5.1.3 then 5.1.2 would remain the latest release from 5.1 branch.

I don't think I understand what you're saying. 🙈 – I don't want to access *updated* builds of a specific release, just any binary for every 5.x ffmpeg release.

> Having said that, all releases are archived here at Github. Browse them via the Tags button. 5.1.1 is at https://github.com/GyanD/codexffmpeg/releases/tag/5.1.1

I missed that, this solves my use case, thank you!
