### ISSUE TITLE
PCR PID AND VIDEO PID always same but in comand both are diffrent

### ISSUE THREAD

**Issue by ansariatif** [GyanD/codexffmpeg#81]
**Coammand**

 -loglevel error  -rtbufsize 100M   -rw_timeout 3000000 -thread_queue_size 4120  -re -i "https://main.clickstreamcdn.com/sp/mr-singh/playlist.m3u8" -filter_complex "[0:v]yadif=0:-1,scale=1920:1080" -map 0:a:0? -codec:v libx264 -pix_fmt yuv420p -b:v 1800k -minrate 1800k -codec:a aac -b:a 128k -ac 2 -ar 44100 -r 25 -g 60 -bf 3 -me_method hex -sc_threshold 40  -x264-params keyint=60:min-keyint=24:bframes=3:me=hex:scenecut=40 -x264opts colormatrix=bt709 -streamid 0:512 -streamid 1:640 -mpegts_original_network_id 1 -mpegts_transport_stream_id 1 -mpegts_service_id 1280 -mpegts_pmt_start_pid 256 -mpegts_start_pid 800 -metadata service_provider="qwe" -metadata service_name="ew"   -cmp 2 -subcmp 2 -mbd rd -copyinkf  -copyts -flags +ilme -flags2 +fast -fflags +genpts -pcr_period 20 -pat_period 0.10 -sdt_period 0.25 -flush_packets 0 -f mpegts -mpegts_flags +pat_pmt_at_frames -mpegts_start_pid 800  -muxrate 2500k -packetsize 1316 -tables_version 10 "udp://224.2.2.2:2002?pkt_size=1316&buffer_size=65535&ttl=2&bitrate=2500000&burst_bits=100000"

**output in streamguru analyzer**

![image](https://user-images.githubusercontent.com/13900715/212909506-e049eeb2-5843-44ae-a044-6c63ee100c38.png)

i want both must have diifrent

**Comment by GyanD** [comment]
Usage questions belong on a forum like SuperUser or reddit r/ffmpeg.

FFmpeg will take the id from the first video stream. That behaviour is hardcoded.
