### ISSUE TITLE
Can’t find library version used for the static build.

### ISSUE THREAD

**Issue by eromawyn** [GyanD/codexffmpeg#82]
Hi,

I wonder what version of libaom-av1 my ffmpeg build was compiled with ... 

I couldn’t find this when encoding, I got : 
```
  Stream #0:0: Video: av1, yuv420p(tv, progressive), 720x576 [SAR 64:45 DAR 16:9], q=2-31, 25 fps, 1k tbn
    Metadata:
      encoder         : Lavc59.37.100 libaom-av1
```

I also couldn’t find any switch on ffmpeg CLI which would give me this information.

Ok, no problem, maybe on your website. No more.

So, in the README.txt ? Lots of libraries, but not their versions ?

So, is there a way to have this info somewhere ? If yes, it would be nice to add how to get this information on the website.
If not, it would be nice to include it in README.txt, another file in the 7z file, or on the website.

And finally, if it is build against a libaom-av1 version before 3.5, it’s worth upgrading the library in the next build.

**Comment by eromawyn** [comment]
Ok, I managed to get the information I was interested in (libaom-av1). It was very readable in fact, even in cyan color, when encoding and/or running ffprobe : 
``
[libaom-av1 @ 000001ed9e2bc040] 3.5.0-242-g6ed0c7a32
```
So, it’s 3.5.0, so perfect, recent version. 

Still, there should be a better way to recover a library version information (and I’m not sure if all statically linked librares will show theirs versions this way), so I leave the issue open. (On website, and/or in README.txt or a new file in the package).

**Comment by GyanD** [comment]
These have to be manually extracted and compiled. I'll put it on my todo. Will probably be a couple of months.
