### ISSUE TITLE
Windows ARM64

### ISSUE THREAD

**Issue by Beyley** [GyanD/codexffmpeg#84]
Could you provide Windows on ARM builds of FFmpeg? I specifically need ARM64 shared libraries, to interop with from C#

**Comment by GyanD** [comment]
Probably not. I'm not sure I have all the build tooling required, and yours is the first request.

**Comment by ArminiusTux** [comment]
If this whish list is still open, I would also request WinARM64 builds of ffmpeg.☝️
They would nicely fit under the compression branch of [this Christmas tree](https://armrepo.ver.lt/). 🎄
