### ISSUE TITLE
slight frame naming issue for animations not beginning at 0

### ISSUE THREAD

**Issue by anrowa** [GyanD/codexffmpeg#85]
Hi, artist here using this to export my animations as gifs out of krita. I had a slight hiccup with it just trying to export a specific segment of animation, frames 34-85. Since the program names frames starting with 0000 however, when it got to the actual giffing part (I am an artist not a coder, I can guess at process but idk the real terms for stuff) it was just grabbing the frames that fit in the set 34-85 range based on the way it had named them, which doesn't reflect their placement in my original file. So, I was stuck with a gif only a few frames long and a lot of spare frames. Once I realized what was going on it was easy enough to take those frames out and put them in their own layer starting at 0, so that's all right, but figured I'd let you know!

**Comment by GyanD** [comment]
If you're using ffmpeg through Krita's interface, then Krita is best placed for support.
If you're using ffmpeg directly, then usage questions belong on https://video.stackexchange.com/ or https://www.reddit.com/r/ffmpeg/
