### ISSUE TITLE
ffprobe does not recognize subtitle manifests

### ISSUE THREAD

**Issue by GrampaWildWilly** [GyanD/codexffmpeg#88]
I have observed this problem in several releases of ffmpeg/ffprobe over the past few years but I'm only just now getting annoyed enough to speak up about it.  Every time I run ffprobe on an HLS master manifest that happens to contain a reference to a subtitles stream, I get this error (which also by the way shows the version of ffprobe I'm running now, but this is, as I say, not a new issue):

ffprobe version 2023-03-02-git-814178f926-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  3.100 / 58.  3.100
  libavcodec     60.  5.100 / 60.  5.100
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  4.100 /  9.  4.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[hls @ 000000000057a340] Skip ('#EXT-X-VERSION:4')
[hls @ 000000000057a340] Can't support the subtitle(uri: https://sdn-global-streaming-cache-3qsdn-medici.akamaized.net/9378/files/22/12/27/7007027/9378-w94Ttc8NyCjHfWY-drm-aes.ism/9378-w94Ttc8NyCjHfWY-drm-aes-textstream_fre=1000.m3u8)

But this is bogus.  When I run this command:

ffmpeg -i "the URL from the ffprobe error message" Subs.vtt

I get a perfectly lovely captions file in Subs.vtt.  VLC correctly displays the captions when I play the associated video that is in the rest of the ffprobe report, a report that I am not displaying in full here.

So I would like ffprobe to quit generating this bogus error message & instead provide some meaningful information about the subtitles.  It is obviously not true that the subtitles are not supported.

**Comment by GyanD** [comment]
Usage questions belong on https://video.stackexchange.com/ or https://www.reddit.com/r/ffmpeg/
That said, try adding `-strict experimental`.

**Comment by GrampaWildWilly** [comment]
I apologize for mistakenly posting here.  I found the link to here from this page:

https://www.gyan.dev/ffmpeg/builds/

Specifically, this section:

https://www.gyan.dev/ffmpeg/builds/#discussion

It says there that this is one of the places to hold discussions.  There are 2 other choices, but since I already had a GitHub ID for a different application, I chose to post here.  If there are other places where posts should go, please update that page to indicate those other places.  Thank you.

But besides that, I thank you again.  -strict experimental works a treat!  The error message is gone & the captions now show up as Streams within the various Programs of the ffprobe report.  So much simpler than the manual method I was using.

Even so, why is this feature still experimental?  Surely you dev folks have enough evidence to promote it to production status.  If I can vote for that somewhere, do please tell me where to do that.

**Comment by GyanD** [comment]
np. The discussion is for issues specifically pertaining to my builds or the site. I will clarify that.
