### ISSUE TITLE
I cannot install Gyan.FFmpeg v6.0 from winget

### ISSUE THREAD

**Issue by ali50m** [GyanD/codexffmpeg#89]
It reports "安装程序哈希不匹配." => Installer hash mismatch.

Environment: Win11 64bit 22H2, Winget v1.4.10173

BTW, I can install Gyan.FFmpeg.Shared (v5.1.2) from winget.

![image](https://user-images.githubusercontent.com/9393831/223157175-11669f6b-fb20-4b11-a361-4150b3d68de5.png)

**Comment by GyanD** [comment]
Was [fixed](https://github.com/microsoft/winget-pkgs/pull/98578) 2 hours ago.
