### ISSUE TITLE
Update Gyan.FFmpeg.Shared on winget to 6.0 release

### ISSUE THREAD

**Issue by FreezyLemon** [GyanD/codexffmpeg#90]
`Gyan.FFmpeg` is already on version 6.0, but `Gyan.FFmpeg.Shared` still hosts version 5.1.2 even though the 6.0 shared build is available on the website:

```
PS C:\Users\user> winget search gyan.ffmpeg
Name            Id                 Version Source
--------------------------------------------------
FFmpeg          Gyan.FFmpeg        6.0     winget
FFmpeg (Shared) Gyan.FFmpeg.Shared 5.1.2   winget
```

**Comment by GyanD** [comment]
Mentioned it in a related issue there.
Note that I don't maintain the package entries at Winget so this should be followed up at https://github.com/microsoft/winget-pkgs/issues
