### ISSUE TITLE
Bangla font is not working properly in video subtitle

### ISSUE THREAD

**Issue by Ariful4593** [GyanD/codexffmpeg#94]
const catchAsyncError = require('../utils/catchAsyncError');
const { spawn } = require('child_process');

exports.addSubtitles = catchAsyncError(async (req, res, next) => {
    const videoFile = `uploads/${req.files.video[0].filename}`;
    const subtitleFile = `uploads/${req.files.subtitle[0].filename}`;
    const outputPath = `uploads/${req.files.video[0].filename}-with-subtitle.mp4`;

    const ffmpeg = spawn('ffmpeg', [
        '-i', videoFile,
        '-vf', `subtitles=${subtitleFile}`,
        '-c:a', 'copy',
        '-preset', 'ultrafast',
        outputPath
    ]);

    ffmpeg.stdout.on('data', data => {
        console.log(`stdout: ${data}`);
    });

    ffmpeg.stderr.on('data', data => {
        console.error(`stderr: ${data}`);
    });

    ffmpeg.on('close', code => {
        console.log(`child process exited with code ${code}`);
        res.send(`Subtitle added to ${outputPath}`);
    });
});

This is what I expecting: পোশাক পাল্টে নাও।

But ffmpeg generated like the below image in video subtitles:
![bangla font issue](https://user-images.githubusercontent.com/65606159/230710868-92867904-9b7c-498e-973f-1a2db6b5a356.png)

Please help to find out what the problem is.

**Comment by GyanD** [comment]
The actual shapes are generated by an external library - harfbuzz, I believe, linked by freetype. Issues with rendering many non-Latin scripts have been reported. So, should be reported there.

**Comment by Ariful4593** [comment]
Okay, thanks.
