### ISSUE TITLE
PATH wrong when install from winget

### ISSUE THREAD

**Issue by GongT** [GyanD/codexffmpeg#95]
Install with ` Gyan.FFmpeg` and restart terminal, ffmpeg.exe still not found.

I found it append this after Path environment: `C:/Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe`

But the right value should be `C:\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.0-full_build\bin`

"ffmpeg-6.0-full_build\bin" is missing.

**Comment by GyanD** [comment]
This is a winget bug. Issue already exists at https://github.com/microsoft/winget-pkgs/issues/95349
