### ISSUE TITLE
libvmaf seems not available

### ISSUE THREAD

**Issue by jdombier** [GyanD/codexffmpeg#97]
Hi,

I tried to run this command with the master or release, essential or full package of ffmpeg.
`ffmpeg.exe  -f lavfi -i color=c=black:s=640x480:d=1 -filter_complex "[0:v][0:v]libvmaf=model=version=vmaf_v0.6.1" -f null -`

I got this error
`[AVFilterGraph @ 00000280ab242100] No such filter: 'libvmaf'
Error initializing complex filters.
Invalid argument`

I don't see it either when I run the command 
`ffmpeg -filters`

It looks like libvmaf is not part of the ffmpeg build.
Could you check this please ?

Thanks,
Jeremy

**Comment by GyanD** [comment]
Add -report and rerun. Share report.

I see libvmaf available in both my 6.0 and git builds.
