### ISSUE TITLE
filter graphs not available.

### ISSUE THREAD

**Issue by amityk77** [GyanD/codexffmpeg#98]
hello,
I am using the following shared build on Windows Plaftorm:

https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z

and trying to use "avfilter_graph_alloc", but getting the following error:

1>FFMpegFile.obj : error LNK2019: unresolved external symbol avfilter_graph_alloc referenced in function "private: int __cdecl common::mediaFiles::ffmpegFiles::FFMpegFile::checkInterlacing(class std::tr1::shared_ptr<struct common::mediaFiles::ffmpegFiles::av_ff_settings>)" (?checkInterlacing@FFMpegFile@ffmpegFiles@mediaFiles@common@@AEAAHV?$shared_ptr@Uav_ff_settings@ffmpegFiles@mediaFiles@common@@@tr1@std@@@Z)

also tried switching to previous version 5.1.2, but the same result.

Please let me know what's missing.?

Regards,
Amit. Khobragade.

**Comment by GyanD** [comment]
The symbol is present and exported in the 6.0 shared build. Check `lib/avfilter-9.def`.

For troubleshooting, use https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?view=msvc-170

Also see the answers at https://stackoverflow.com/q/11701635/

**Comment by amityk77** [comment]
Hello,
Problem solved.
Since I have multiple configuration in projects, I had the wrong configuration with .lib selected.
corrected the same, and now its compilable.
Thanks.
