### ISSUE TITLE
Query: how did you get rav1e working?

### ISSUE THREAD

**Issue by lilnasy** [GyanD/codexffmpeg#99]
Thank you for your execellent work on maintaining the go-to builds for windows. I'm trying to compile a minimal static binary for windows and including rav1e has been a challenge. I get blocked on `ERROR: rav1e >= 0.5.0 not found using pkg-config` except rav1e is available to pkg-config and `--exists rav1e` exits happily.

For more context, I'm using a msys2 + mingw setup on github actions, it's just one file: [workflows/windows.yml](https://github.com/lilnasy/static-ffmpeg-on-actions/actions/runs/5101151710/workflow), and ffmpeg.log is searchable here: [actions log](https://github.com/lilnasy/static-ffmpeg-on-actions/actions/runs/5101151710/jobs/9169823344).

This issue is similar to [BtbN/Ffmpeg-Builds#234](https://github.com/BtbN/FFmpeg-Builds/issues/234), but their solution to ensure 644 permissions for /mingw64/lib/rav1e.a was not effective. 

Curious how you are building/including rav1e.

**Comment by GyanD** [comment]
I see the following in my rav1e.pc

`Libs.private:  -lkernel32 -ladvapi32 -luserenv -lkernel32 -lkernel32 -lws2_32 -lbcrypt`

**Comment by lilnasy** [comment]
Thanks a lot for your help!

I still don;t understand the issue, but my best guess is that the rav1e package in msys2 are busted, and the empty `Libs.private` may be part of the reason why.

I am now compiling from source, and caching to avoid compiling every time.
